---
title: "Selected Projects"
---

### 1. Gender Disparities in Labor Force Analysis (2024)
<a href="https://dinarazhorabek.github.io/ad688-employability-fall25A1-group5/" target="_blank" class="btn btn-outline-secondary btn-sm" style="margin-left:1rem;">Website</a>
<a href="report/AD688 Team 5 - Final Report.pdf" target="_blank" class="btn btn-outline-info btn-sm" style="margin-left:1rem;">Research Paper</a>
<a href="https://www.canva.com/design/DAG639sRGbs/2VEs0-WVFCtsTM9rrpnnsw/edit?utm_content=DAG639sRGbs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
target="_blank" class="btn btn-outline-warning btn-sm" style="margin-left:1rem;">PPT</a>

- *Labor Market Analytics Research Project* | Sep 2025 – Dec 2025
  - Analyzed Lightcast and FRED data in Python, applying regression and ML models to forecast 2024 labor-market trends
  - Built visualizations to assess skill demand, salary patterns, geographic variation, and gender-based differences across U.S. markets
  - Synthesized model results with academic research to deliver actionable insights on hiring behavior and gender disparities

### 2. Factors That Influence Airbnb Prices in Geneva
<a href="report/Geneva-SemesterProject.pdf" target="_blank" class="btn btn-outline-info btn-sm" style="margin-left:1rem;">Research Paper</a>
<a href="https://docs.google.com/presentation/d/1prD3yy9D4gp4bHZKNinXs-br8ZgcmMSEO8GHfaSKT8o/edit?usp=sharing"
target="_blank" class="btn btn-outline-warning btn-sm" style="margin-left:1rem;">PPT</a>

- *Applied Machine Learning for Airbnb Pricing in Geneva* | Sep 2025 – Dec 2025
  - Applied Python for data visualization, regression, k-NN, classification trees, NLP transformers, and clustering to analyze Airbnb pricing in Geneva
  - Engineered features from structured and unstructured listing data to build predictive and market segmentation models
  - Generated actionable insights to inform Airbnb hosts’ pricing decisions and listing strategies, and to support platform-level market segmentation in the Geneva market

### 3. Bangladesh Garment Industry: Health and Environmental Impacts 
<a href="https://drive.google.com/file/d/1TVS8lB6LbdHJQTsjj4K5bVkDQ_5mSXmR/view" target="_blank" class="btn btn-outline-info btn-sm" style="margin-left:1rem;">Research Paper</a>

- *Economics Seminar Research Paper* | Jan 2021 – Mar 2021
  - Conducted a literature review on short- and long-term effects of Bangladesh's garment industry on health and environment
  - Examined workers’ health, safety evaluations, and child labor issues using historical data
  - Proposed strategies to mitigate risks while supporting sustainable industry growth

---
