<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Classification – Nhat Tran</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1db3f541d99483cdc7a0d9cf38862b2c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nhat Tran</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-academics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Academics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-academics">    
        <li>
    <a class="dropdown-item" href="../coursework.html">
 <span class="dropdown-text">Relevant Coursework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../pynotes.html">
 <span class="dropdown-text">Python Notebooks</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../certifications.html"> 
<span class="menu-text">Certifications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-i-logistic-regression-model" id="toc-part-i-logistic-regression-model" class="nav-link active" data-scroll-target="#part-i-logistic-regression-model">Part I: Logistic Regression Model</a>
  <ul class="collapse">
  <li><a href="#for-any-variables-that-need-to-be-dummified-dummify-them-being-sure-to-drop-one-level-as-you-do." id="toc-for-any-variables-that-need-to-be-dummified-dummify-them-being-sure-to-drop-one-level-as-you-do." class="nav-link" data-scroll-target="#for-any-variables-that-need-to-be-dummified-dummify-them-being-sure-to-drop-one-level-as-you-do.">For any variables that need to be dummified, dummify them, being sure to drop one level as you do.</a></li>
  <li><a href="#iteration-1" id="toc-iteration-1" class="nav-link" data-scroll-target="#iteration-1">Iteration #1</a></li>
  <li><a href="#iteration-2" id="toc-iteration-2" class="nav-link" data-scroll-target="#iteration-2">Iteration #2</a></li>
  </ul></li>
  <li><a href="#part-ii-random-forest-model" id="toc-part-ii-random-forest-model" class="nav-link" data-scroll-target="#part-ii-random-forest-model">Part II: Random Forest Model</a></li>
  <li><a href="#part-iii-tableau-dashboard" id="toc-part-iii-tableau-dashboard" class="nav-link" data-scroll-target="#part-iii-tableau-dashboard">Part III: Tableau Dashboard</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Classification</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Will this Passholder Renew for Next Season?</strong></p>
<section id="part-i-logistic-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="part-i-logistic-regression-model">Part I: Logistic Regression Model</h2>
<div id="f4b9b679-9b24-4eb4-b930-0cefd55f9aeb" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import necessary functions to use</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="311f1a11-9229-402c-88d7-fc29b5c9a6eb" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>passholder <span class="op">=</span> pd.read_csv(<span class="st">"/Users/nhattran/Downloads/MSBA/METAD654 - Marketing Analytics/assignment 4/lobsterland_passholders_dataset_25.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="36b83b27-4a7a-4eb3-a385-35ff9b75e52c" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>passholder.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<th data-quarto-table-cell-role="th">Home_State</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction</th>
<th data-quarto-table-cell-role="th">Referral_Source</th>
<th data-quarto-table-cell-role="th">Dining_Plan</th>
<th data-quarto-table-cell-role="th">Renewed_Pass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>59.000000</td>
<td>3.000000</td>
<td>394.780000</td>
<td>4.606232</td>
<td>4.000000</td>
<td>44.200000</td>
<td>1.900000</td>
<td>VT</td>
<td>Thrill</td>
<td>Social Media</td>
<td>Upgraded</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>27.846318</td>
<td>1.064843</td>
<td>172.541334</td>
<td>2.102264</td>
<td>2.000819</td>
<td>37.103840</td>
<td>21.709631</td>
<td>NH</td>
<td>Other</td>
<td>Ad/Other</td>
<td>NaN</td>
<td>1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>18.000000</td>
<td>5.926144</td>
<td>151.731274</td>
<td>3.365074</td>
<td>1.019084</td>
<td>61.827722</td>
<td>21.892411</td>
<td>VT</td>
<td>Entertainment</td>
<td>Social Media</td>
<td>Upgraded</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>25.000000</td>
<td>12.000000</td>
<td>251.300000</td>
<td>3.458663</td>
<td>1.000000</td>
<td>41.800000</td>
<td>6.600000</td>
<td>NY</td>
<td>Other</td>
<td>Friend</td>
<td>Upgraded</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>66.206178</td>
<td>4.038141</td>
<td>197.686695</td>
<td>2.985864</td>
<td>3.955755</td>
<td>61.174332</td>
<td>29.981959</td>
<td>NJ</td>
<td>Entertainment</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="ae3b912c-ca6b-4ba0-ae74-2acaeca97723" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>passholder.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Age                       1000 non-null   float64
 1   Previous_Visits           1000 non-null   float64
 2   Total_Spend_2024          1000 non-null   float64
 3   Feedback_Score            1000 non-null   float64
 4   Gold_Zone_Visits          1000 non-null   float64
 5   Email_Engagement_Score    1000 non-null   float64
 6   Distance_From_Park_Miles  1000 non-null   float64
 7   Home_State                1000 non-null   object 
 8   Preferred_Attraction      1000 non-null   object 
 9   Referral_Source           1000 non-null   object 
 10  Dining_Plan               667 non-null    object 
 11  Renewed_Pass              1000 non-null   int64  
dtypes: float64(7), int64(1), object(4)
memory usage: 93.9+ KB</code></pre>
</div>
</div>
<ul>
<li><p><strong>Numerical Variables:</strong> Age, Previous_Visits, Total_Spend_2024, Feedback_Score, Gold_Zone_Visits, Email_Engagement_Score, Distance_From_Park_Miles</p></li>
<li><p><strong>Categorical Variables:</strong> Home_State, Preferred_Attraction, Referral_Source, Dining_Plan</p></li>
<li><p><strong>Renewed_Pass:</strong> binary target (0/1 or bool); treat as outcome, not a predictor.</p></li>
</ul>
<div id="1dff0861-dcf4-4fe2-91be-013543e88b30" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the variables to the categorical data type</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>passholder[[<span class="st">'Home_State'</span>, <span class="st">'Preferred_Attraction'</span>, <span class="st">'Referral_Source'</span>, <span class="st">'Dining_Plan'</span>]] <span class="op">=</span> passholder[[<span class="st">'Home_State'</span>, <span class="st">'Preferred_Attraction'</span>, <span class="st">'Referral_Source'</span>, <span class="st">'Dining_Plan'</span>]].astype(<span class="st">'category'</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the Renewed_Pass to bool</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>passholder[[<span class="st">'Renewed_Pass'</span>]] <span class="op">=</span> passholder[[<span class="st">'Renewed_Pass'</span>]].astype(<span class="st">'bool'</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Double-check to see if all the variables return to the correct type</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>passholder.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype   
---  ------                    --------------  -----   
 0   Age                       1000 non-null   float64 
 1   Previous_Visits           1000 non-null   float64 
 2   Total_Spend_2024          1000 non-null   float64 
 3   Feedback_Score            1000 non-null   float64 
 4   Gold_Zone_Visits          1000 non-null   float64 
 5   Email_Engagement_Score    1000 non-null   float64 
 6   Distance_From_Park_Miles  1000 non-null   float64 
 7   Home_State                1000 non-null   category
 8   Preferred_Attraction      1000 non-null   category
 9   Referral_Source           1000 non-null   category
 10  Dining_Plan               667 non-null    category
 11  Renewed_Pass              1000 non-null   bool    
dtypes: bool(1), category(4), float64(7)
memory usage: 60.3 KB</code></pre>
</div>
</div>
<div id="e2c1d3cb-1afe-4f44-a2f6-790fdbad4794" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>passholder[<span class="st">'Renewed_Pass'</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>Renewed_Pass
True     580
False    420
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>By using the value_counts() function, I found that out of 1,000 passholders, 580 renewed their passes (True) and 420 did not (False). This means that about 58% of customers chose to renew, while 42% did not. Understanding this distribution helps LobsterLand’s management identify the current renewal rate and focus on strategies to increase it—for example, by attracting non-renewers with targeted promotions or loyalty programs.</p>
<section id="missing-values" class="level4">
<h4 class="anchored" data-anchor-id="missing-values">Missing values</h4>
<div id="721dc2d3-4ee9-435d-a0e4-0582ce08db45" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>passholder.isnull().<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>Age                           0
Previous_Visits               0
Total_Spend_2024              0
Feedback_Score                0
Gold_Zone_Visits              0
Email_Engagement_Score        0
Distance_From_Park_Miles      0
Home_State                    0
Preferred_Attraction          0
Referral_Source               0
Dining_Plan                 333
Renewed_Pass                  0
dtype: int64</code></pre>
</div>
</div>
<div id="fd717ea1-3090-4313-b3c1-9f3784d297bf" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>passholder[<span class="st">'Dining_Plan'</span>].head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>0    Upgraded
1         NaN
2    Upgraded
3    Upgraded
4    Upgraded
Name: Dining_Plan, dtype: category
Categories (1, object): ['Upgraded']</code></pre>
</div>
</div>
<div id="bff2b81f-44e2-40d7-8f1b-202d5e5e0890" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add category 'None' to 'Dining_Plan' variable then fill any NaN values with 'None'</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>passholder[<span class="st">'Dining_Plan'</span>] <span class="op">=</span> passholder[<span class="st">'Dining_Plan'</span>].cat.add_categories([<span class="st">'None'</span>]).fillna(<span class="st">'None'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="8f4b5954-07f6-472a-be49-431a4e687bfe" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Double-check to see if 'Dining_Plan' variable still has any missing values</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>passholder[<span class="st">'Dining_Plan'</span>].isnull().<span class="bu">sum</span>()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>passholder[<span class="st">'Dining_Plan'</span>].unique</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>&lt;bound method Series.unique of 0      Upgraded
1          None
2      Upgraded
3      Upgraded
4      Upgraded
         ...   
995    Upgraded
996    Upgraded
997    Upgraded
998    Upgraded
999    Upgraded
Name: Dining_Plan, Length: 1000, dtype: category
Categories (2, object): ['Upgraded', 'None']&gt;</code></pre>
</div>
</div>
<p>According to the dataset description, the Dining_Plan variable indicates whether a passholder purchased a Lobster Land food plan, with two possible options: ‘None’ and ‘Upgraded’, where Upgraded includes both the Standard and Premium tiers. There are 333 missing values in this variable, which likely represent passholders who did not purchase any dining plan. For consistency, I replaced all missing values with ‘None’ to accurately reflect this behavior and ensure the data remains complete for analysis.</p>
</section>
<section id="impossible-values" class="level4">
<h4 class="anchored" data-anchor-id="impossible-values">Impossible values</h4>
<div id="e015960f-107c-4eab-b6c3-d363451400d4" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>passholder.describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>1000.000000</td>
<td>1000.000000</td>
<td>1000.000000</td>
<td>1000.000000</td>
<td>1000.000000</td>
<td>1000.000000</td>
<td>1000.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>45.843471</td>
<td>4.739685</td>
<td>211.420490</td>
<td>3.231483</td>
<td>2.045040</td>
<td>50.055373</td>
<td>30.708474</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>16.278317</td>
<td>2.291030</td>
<td>105.815989</td>
<td>0.992790</td>
<td>1.411507</td>
<td>19.941021</td>
<td>17.108942</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>18.000000</td>
<td>0.000000</td>
<td>-39.950000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>-8.100000</td>
<td>0.100000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>33.000000</td>
<td>3.000000</td>
<td>142.775364</td>
<td>2.585852</td>
<td>1.000000</td>
<td>35.975548</td>
<td>18.300000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>46.278713</td>
<td>5.000000</td>
<td>199.942199</td>
<td>3.306673</td>
<td>2.000000</td>
<td>50.450000</td>
<td>29.837614</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>61.000000</td>
<td>6.005339</td>
<td>274.070000</td>
<td>3.826473</td>
<td>3.000000</td>
<td>62.783218</td>
<td>43.797075</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>74.000000</td>
<td>12.000000</td>
<td>559.830000</td>
<td>5.000000</td>
<td>8.000000</td>
<td>108.300000</td>
<td>87.100000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="are-there-any-values-in-this-dataset-that-appear-to-be-impossible-if-so-why-if-not-why-not" class="level4">
<h4 class="anchored" data-anchor-id="are-there-any-values-in-this-dataset-that-appear-to-be-impossible-if-so-why-if-not-why-not">Are there any values in this dataset that appear to be impossible? If so, why? If not, why not?</h4>
<div id="8187c2e4-a11d-47a5-beb6-ec126c0b198a" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View rows with negative Total_Spend_2024 and Email_Engagement_Score outside of range 0-100</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>passholder[(passholder[<span class="st">'Total_Spend_2024'</span>] <span class="op">&lt;</span> <span class="dv">0</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<th data-quarto-table-cell-role="th">Home_State</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction</th>
<th data-quarto-table-cell-role="th">Referral_Source</th>
<th data-quarto-table-cell-role="th">Dining_Plan</th>
<th data-quarto-table-cell-role="th">Renewed_Pass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">228</th>
<td>34.632594</td>
<td>2.948977</td>
<td>-1.000297</td>
<td>3.072944</td>
<td>0.965401</td>
<td>53.158994</td>
<td>53.764673</td>
<td>ME</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">280</th>
<td>34.092198</td>
<td>2.986994</td>
<td>-0.508581</td>
<td>3.033482</td>
<td>0.977585</td>
<td>52.641486</td>
<td>53.059526</td>
<td>ME</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">465</th>
<td>54.000000</td>
<td>6.000000</td>
<td>-39.950000</td>
<td>3.142010</td>
<td>4.000000</td>
<td>58.900000</td>
<td>10.300000</td>
<td>NY</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">477</th>
<td>34.430205</td>
<td>2.951587</td>
<td>-0.751035</td>
<td>3.027981</td>
<td>0.996431</td>
<td>51.767003</td>
<td>52.981610</td>
<td>ME</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">485</th>
<td>33.764976</td>
<td>2.934015</td>
<td>-1.852003</td>
<td>3.043365</td>
<td>1.004973</td>
<td>53.342196</td>
<td>53.162699</td>
<td>ME</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">493</th>
<td>26.000000</td>
<td>5.000000</td>
<td>-2.230000</td>
<td>3.555003</td>
<td>2.000000</td>
<td>55.600000</td>
<td>27.800000</td>
<td>VT</td>
<td>Thrill</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">499</th>
<td>33.327308</td>
<td>2.984666</td>
<td>-1.439116</td>
<td>3.037064</td>
<td>0.967710</td>
<td>53.574152</td>
<td>53.156368</td>
<td>ME</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">573</th>
<td>42.000000</td>
<td>4.000000</td>
<td>-23.910000</td>
<td>3.239964</td>
<td>6.000000</td>
<td>66.800000</td>
<td>32.500000</td>
<td>MA</td>
<td>Other</td>
<td>Social Media</td>
<td>Upgraded</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">750</th>
<td>33.715105</td>
<td>3.037335</td>
<td>-3.514091</td>
<td>3.059007</td>
<td>1.022880</td>
<td>53.124907</td>
<td>53.273690</td>
<td>ME</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">761</th>
<td>52.000000</td>
<td>4.000000</td>
<td>-3.180000</td>
<td>3.991413</td>
<td>4.000000</td>
<td>66.700000</td>
<td>51.200000</td>
<td>NJ</td>
<td>Entertainment</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">884</th>
<td>34.367413</td>
<td>3.052398</td>
<td>-1.531736</td>
<td>3.076422</td>
<td>0.990859</td>
<td>52.913776</td>
<td>54.164073</td>
<td>ME</td>
<td>Other</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="fb754bce-d205-48dd-af20-d08c5064ec8c" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View rows with Email_Engagement_Score outside of range 0-100</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>passholder[(passholder[<span class="st">'Email_Engagement_Score'</span>] <span class="op">&lt;</span> <span class="dv">0</span>) <span class="op">|</span> (passholder[<span class="st">'Email_Engagement_Score'</span>] <span class="op">&gt;</span> <span class="dv">100</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<th data-quarto-table-cell-role="th">Home_State</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction</th>
<th data-quarto-table-cell-role="th">Referral_Source</th>
<th data-quarto-table-cell-role="th">Dining_Plan</th>
<th data-quarto-table-cell-role="th">Renewed_Pass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">308</th>
<td>42.0</td>
<td>2.0</td>
<td>385.92</td>
<td>2.830563</td>
<td>1.0</td>
<td>102.9</td>
<td>9.4</td>
<td>MA</td>
<td>Other</td>
<td>Ad/Other</td>
<td>None</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">379</th>
<td>21.0</td>
<td>4.0</td>
<td>345.79</td>
<td>2.868348</td>
<td>1.0</td>
<td>-8.1</td>
<td>39.3</td>
<td>ME</td>
<td>Thrill</td>
<td>Ad/Other</td>
<td>None</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">418</th>
<td>37.0</td>
<td>4.0</td>
<td>339.49</td>
<td>3.264726</td>
<td>1.0</td>
<td>105.3</td>
<td>34.9</td>
<td>VT</td>
<td>Entertainment</td>
<td>Ad/Other</td>
<td>None</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">902</th>
<td>55.0</td>
<td>4.0</td>
<td>150.17</td>
<td>4.445888</td>
<td>0.0</td>
<td>108.3</td>
<td>41.9</td>
<td>NY</td>
<td>Thrill</td>
<td>Ad/Other</td>
<td>Upgraded</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="9393762b-6b94-43f9-9100-abf4ac343be7" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the negative Total_Spend_2024 value by filtering it to be greater than 0</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>passholder <span class="op">=</span> passholder[passholder[<span class="st">'Total_Spend_2024'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The negative values in Total_Spend_2024 range from –39 to –0.50, which isn’t much and could possibly represent small refunds from Lobster Land to customers. However, negative spending contradicts the variable’s definition, which means to capture the total amount spent by a passholder during the season. Even if these small negatives reflect refunds, they should be tracked separately to avoid misrepresenting overall spending behavior. Since there are only 11 negative values, accounting for less than 1.5% of the dataset, I decided to drop them to maintain a clean and accurate dataset for further analysis.</p>
<div id="c891aa01-e2c9-4679-9db7-cf4dd27c86b6" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cap Email_Engagement_Score at 100 for those exceeding the 100 range</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>passholder[<span class="st">'Email_Engagement_Score'</span>] <span class="op">=</span> passholder[<span class="st">'Email_Engagement_Score'</span>].clip(upper<span class="op">=</span><span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I capped the Email_Engagement_Score at 100 because a few users had scores slightly above that limit (102.9; 105.3; 108.3), likely due to very high engagement. All three users visited Lobster Land at least twice, showing a 100% return rate after their first visit, which is possibly influenced by follow-up emails. Clipping these minor outliers keeps the metric consistent with its defined scale while preserving meaningful behavioral signals in the data.</p>
<div id="69deb206-db20-4b80-a5c4-064daa0677cd" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the negative Email_Engagement_Score value by filtering it to be greater than 0</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>passholder <span class="op">=</span> passholder[passholder[<span class="st">'Email_Engagement_Score'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I decided to drop the row with a negative Email_Engagement_Score because it’s supposed to stay within the 0–100 range, and negative values don’t have any meaningful interpretation. Since only one row is affected, I felt removing it would keep the dataset clean without introducing bias and ensure consistent analysis.</p>
<div id="7d12f706-6eb9-4db6-8f93-73d65165be61" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-check to see if the dataset contains any nan value</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>passholder.isnull().<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>Age                         0
Previous_Visits             0
Total_Spend_2024            0
Feedback_Score              0
Gold_Zone_Visits            0
Email_Engagement_Score      0
Distance_From_Park_Miles    0
Home_State                  0
Preferred_Attraction        0
Referral_Source             0
Dining_Plan                 0
Renewed_Pass                0
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="examining-correlations" class="level4">
<h4 class="anchored" data-anchor-id="examining-correlations">Examining correlations</h4>
</section>
<section id="build-a-correlation-table-to-examine-the-correlations-among-your-numeric-independent-variables." class="level4">
<h4 class="anchored" data-anchor-id="build-a-correlation-table-to-examine-the-correlations-among-your-numeric-independent-variables.">Build a correlation table to examine the correlations among your numeric independent variables.</h4>
<div id="7f5aafce-77fa-4477-ba30-869c3e1683a0" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out numeric variables to examine the correlations</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>numeric_vars <span class="op">=</span> passholder.select_dtypes(include<span class="op">=</span>[<span class="st">'float64'</span>, <span class="st">'int64'</span>])</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation table with numeric variables from the dataset</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>corr_table <span class="op">=</span> numeric_vars.corr()</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(corr_table.<span class="bu">round</span>(<span class="dv">3</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            Age  Previous_Visits  Total_Spend_2024  Feedback_Score  Gold_Zone_Visits  Email_Engagement_Score  Distance_From_Park_Miles
Age                       1.000            0.072             0.135           0.009             0.020                  -0.037                     0.100
Previous_Visits           0.072            1.000             0.054          -0.070            -0.084                  -0.071                    -0.094
Total_Spend_2024          0.135            0.054             1.000           0.046            -0.054                  -0.001                     0.065
Feedback_Score            0.009           -0.070             0.046           1.000             0.027                  -0.092                    -0.033
Gold_Zone_Visits          0.020           -0.084            -0.054           0.027             1.000                   0.023                    -0.092
Email_Engagement_Score   -0.037           -0.071            -0.001          -0.092             0.023                   1.000                    -0.093
Distance_From_Park_Miles  0.100           -0.094             0.065          -0.033            -0.092                  -0.093                     1.000</code></pre>
</div>
</div>
<div id="edf9c4ad-9b68-40b9-9d3f-1ef293df388f" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the correlation table in heatmap</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">6</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr_table, annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'coolwarm'</span>, fmt<span class="op">=</span><span class="st">".2f"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Correlation Heatmap of Numeric Variables"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="classification_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="are-there-any-correlations-here-that-are-so-high-as-to-present-a-likely-problem-with-multicollinearity" class="level4">
<h4 class="anchored" data-anchor-id="are-there-any-correlations-here-that-are-so-high-as-to-present-a-likely-problem-with-multicollinearity">Are there any correlations here that are so high as to present a likely problem with multicollinearity?</h4>
<p>The correlation table indicates that none of the variables are strongly related to one another, as all coefficients are well below the typical threshold for multicollinearity (r ≥ 0.8). The highest correlation, 0.135 between Age and Total_Spend_2024 indicating older renewers tend to spend more than the younger audience, is too weak to raise any concerns. Therefore, I can keep all numeric predictors for the modeling stage.</p>
</section>
<section id="for-any-variables-that-need-to-be-dummified-dummify-them-being-sure-to-drop-one-level-as-you-do." class="level3">
<h3 class="anchored" data-anchor-id="for-any-variables-that-need-to-be-dummified-dummify-them-being-sure-to-drop-one-level-as-you-do.">For any variables that need to be dummified, dummify them, being sure to drop one level as you do.</h3>
<div id="7ac3e87a-fe4c-497b-90e5-6ff80a4827f1" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dummify all categorical variables and dropping one category per variable to avoid multicollinearity</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>passholder <span class="op">=</span> pd.get_dummies(passholder, columns<span class="op">=</span>[</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State'</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Preferred_Attraction'</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Referral_Source'</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Dining_Plan'</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>], drop_first<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="fd988ac3-d0ee-4d88-a8a2-af92eb74d775" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>passholder.head(<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<th data-quarto-table-cell-role="th">Renewed_Pass</th>
<th data-quarto-table-cell-role="th">Home_State_ME</th>
<th data-quarto-table-cell-role="th">Home_State_NH</th>
<th data-quarto-table-cell-role="th">Home_State_NJ</th>
<th data-quarto-table-cell-role="th">Home_State_NY</th>
<th data-quarto-table-cell-role="th">Home_State_VT</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Other</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Thrill</th>
<th data-quarto-table-cell-role="th">Referral_Source_Friend</th>
<th data-quarto-table-cell-role="th">Referral_Source_Social Media</th>
<th data-quarto-table-cell-role="th">Dining_Plan_None</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>59.000000</td>
<td>3.000000</td>
<td>394.780000</td>
<td>4.606232</td>
<td>4.000000</td>
<td>44.200000</td>
<td>1.900000</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>27.846318</td>
<td>1.064843</td>
<td>172.541334</td>
<td>2.102264</td>
<td>2.000819</td>
<td>37.103840</td>
<td>21.709631</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>18.000000</td>
<td>5.926144</td>
<td>151.731274</td>
<td>3.365074</td>
<td>1.019084</td>
<td>61.827722</td>
<td>21.892411</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>25.000000</td>
<td>12.000000</td>
<td>251.300000</td>
<td>3.458663</td>
<td>1.000000</td>
<td>41.800000</td>
<td>6.600000</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>66.206178</td>
<td>4.038141</td>
<td>197.686695</td>
<td>2.985864</td>
<td>3.955755</td>
<td>61.174332</td>
<td>29.981959</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>After dummifying the categorical variables, I set the following reference levels: Home_State – MA, Preferred_Attraction – Entertainment, Referral_Source – Ad/Other, and Dining_Plan – Upgraded. These serve as the baseline categories against which other levels are compared in the model. The Renewed_Pass variable is already numeric and binary, so it does not require dummification.</p>
<section id="create-a-data-partition.-assign-40-of-your-rows-to-your-test-set-and-60-to-your-training-set." class="level4">
<h4 class="anchored" data-anchor-id="create-a-data-partition.-assign-40-of-your-rows-to-your-test-set-and-60-to-your-training-set.">Create a data partition. Assign 40% of your rows to your test set, and 60% to your training set.</h4>
<div id="37855b73-5e5f-4e14-b7e5-fa9cd37925e6" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>train_df, test_df <span class="op">=</span> train_test_split(passholder, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">156</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training set size: </span><span class="sc">{</span><span class="bu">len</span>(train_df)<span class="sc">}</span><span class="ss"> rows"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test set size: </span><span class="sc">{</span><span class="bu">len</span>(test_df)<span class="sc">}</span><span class="ss"> rows"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training set size: 592 rows
Test set size: 396 rows</code></pre>
</div>
</div>
<p>For the random seed, I chose 156 because it matches the last three digits of my BUID. Using a personal but simple reference like this helps ensure consistency while keeping the seed easy to remember. It also guarantees that my results are reproducible if I need to rerun the analysis.</p>
</section>
<section id="compare-the-mean-values-of-the-variables-in-the-dataset-after-grouping-by-renewed_pass." class="level4">
<h4 class="anchored" data-anchor-id="compare-the-mean-values-of-the-variables-in-the-dataset-after-grouping-by-renewed_pass.">Compare the mean values of the variables in the dataset after grouping by Renewed_Pass.</h4>
<div id="38483ebd-9999-4ece-8f07-bd2c5ef66c1f" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change Renewed_Pass to Class 0/1</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>passholder[<span class="st">'Renewed_Pass'</span>] <span class="op">=</span> passholder[<span class="st">'Renewed_Pass'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>passholder.groupby(<span class="st">'Renewed_Pass'</span>).mean(numeric_only<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<th data-quarto-table-cell-role="th">Home_State_ME</th>
<th data-quarto-table-cell-role="th">Home_State_NH</th>
<th data-quarto-table-cell-role="th">Home_State_NJ</th>
<th data-quarto-table-cell-role="th">Home_State_NY</th>
<th data-quarto-table-cell-role="th">Home_State_VT</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Other</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Thrill</th>
<th data-quarto-table-cell-role="th">Referral_Source_Friend</th>
<th data-quarto-table-cell-role="th">Referral_Source_Social Media</th>
<th data-quarto-table-cell-role="th">Dining_Plan_None</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Renewed_Pass</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>47.381249</td>
<td>4.672605</td>
<td>217.665995</td>
<td>3.176391</td>
<td>2.014964</td>
<td>51.457782</td>
<td>30.060697</td>
<td>0.110577</td>
<td>0.127404</td>
<td>0.165865</td>
<td>0.201923</td>
<td>0.290865</td>
<td>0.454327</td>
<td>0.348558</td>
<td>0.194712</td>
<td>0.211538</td>
<td>0.358173</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>44.929268</td>
<td>4.811163</td>
<td>210.848800</td>
<td>3.272654</td>
<td>2.067988</td>
<td>48.989534</td>
<td>30.889094</td>
<td>0.159091</td>
<td>0.173077</td>
<td>0.125874</td>
<td>0.178322</td>
<td>0.208042</td>
<td>0.477273</td>
<td>0.325175</td>
<td>0.145105</td>
<td>0.225524</td>
<td>0.319930</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="from-the-results-you-see-here-choose-any-three-independent-variables-from-the-dataset-and-speculate-about-their-likely-impact-on-the-result-do-you-think-this-variable-will-be-strongly-impactful" class="level4">
<h4 class="anchored" data-anchor-id="from-the-results-you-see-here-choose-any-three-independent-variables-from-the-dataset-and-speculate-about-their-likely-impact-on-the-result-do-you-think-this-variable-will-be-strongly-impactful">From the results you see here, choose any THREE independent variables from the dataset, and speculate about their likely impact on the result – do you think this variable will be strongly impactful?</h4>
<p>I chose these three variables: <strong>Email_Engagement_Score, Total_Spend_2024,</strong> and <strong>Dining_Plan_None</strong> because they each capture different aspects of customer behavior that could influence renewal decisions. <strong>Email_Engagement_Score</strong> reflects digital interaction and communication responsiveness, <strong>Total_Spend_2024</strong> shows spending patterns for each visitors, and <strong>Dining_Plan_None</strong> indicates spending habits and overall commitment to the park experience. Together, these variables provide a balanced mix of behavioral, experiential, and transactional factors that could help explain differences between renewers and non-renewers.</p>
<ul>
<li><strong>Email_Engagement_Score:</strong> Non-renewers have a slightly higher average score (51.45) than renewers (48.98). This suggests that email engagement may not directly drive renewal, or that more engaged users are more critical.</li>
<li><strong>Total_Spend_2024:</strong> Non-renewers spent slightly more on average in 2024 (\$217.67) than renewers (\$210.85), which is unexpected if we assume higher spend reflects stronger loyalty. This could suggest that one-time high spenders don’t necessarily return, or that renewers are more consistent but spend less per season.</li>
<li><strong>Dining_Plan_None:</strong> Non-renewers are more likely to have no dining plan (35.81%) compared to renewers (31.99%), suggesting that opting out of the food plan may correlate with lower overall commitment or value perception.</li>
</ul>
</section>
</section>
<section id="iteration-1" class="level3">
<h3 class="anchored" data-anchor-id="iteration-1">Iteration #1</h3>
<section id="build-a-logistic-regression-model-using-statsmodels-with-the-outcome-variable-renewed_pass.-use-the-rest-of-the-remaining-variables-from-the-dataset-as-inputs.-remember-to-use-only-your-training-data-to-build-this-model." class="level4">
<h4 class="anchored" data-anchor-id="build-a-logistic-regression-model-using-statsmodels-with-the-outcome-variable-renewed_pass.-use-the-rest-of-the-remaining-variables-from-the-dataset-as-inputs.-remember-to-use-only-your-training-data-to-build-this-model.">Build a logistic regression model using statsmodels, with the outcome variable ‘Renewed_Pass’. Use the rest of the remaining variables from the dataset as inputs. Remember to use only your training data to build this model.</h4>
<div id="769186ec-1c4e-44f1-97fa-e560232c39a1" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>passholder.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<th data-quarto-table-cell-role="th">Renewed_Pass</th>
<th data-quarto-table-cell-role="th">Home_State_ME</th>
<th data-quarto-table-cell-role="th">Home_State_NH</th>
<th data-quarto-table-cell-role="th">Home_State_NJ</th>
<th data-quarto-table-cell-role="th">Home_State_NY</th>
<th data-quarto-table-cell-role="th">Home_State_VT</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Other</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Thrill</th>
<th data-quarto-table-cell-role="th">Referral_Source_Friend</th>
<th data-quarto-table-cell-role="th">Referral_Source_Social Media</th>
<th data-quarto-table-cell-role="th">Dining_Plan_None</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>59.000000</td>
<td>3.000000</td>
<td>394.780000</td>
<td>4.606232</td>
<td>4.000000</td>
<td>44.200000</td>
<td>1.900000</td>
<td>0</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>27.846318</td>
<td>1.064843</td>
<td>172.541334</td>
<td>2.102264</td>
<td>2.000819</td>
<td>37.103840</td>
<td>21.709631</td>
<td>1</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>18.000000</td>
<td>5.926144</td>
<td>151.731274</td>
<td>3.365074</td>
<td>1.019084</td>
<td>61.827722</td>
<td>21.892411</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>25.000000</td>
<td>12.000000</td>
<td>251.300000</td>
<td>3.458663</td>
<td>1.000000</td>
<td>41.800000</td>
<td>6.600000</td>
<td>0</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>66.206178</td>
<td>4.038141</td>
<td>197.686695</td>
<td>2.985864</td>
<td>3.955755</td>
<td>61.174332</td>
<td>29.981959</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="d217f997-ee70-4acb-afd5-8c1b9570640c" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_df.dtypes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Age                             float64
Previous_Visits                 float64
Total_Spend_2024                float64
Feedback_Score                  float64
Gold_Zone_Visits                float64
Email_Engagement_Score          float64
Distance_From_Park_Miles        float64
Renewed_Pass                       bool
Home_State_ME                      bool
Home_State_NH                      bool
Home_State_NJ                      bool
Home_State_NY                      bool
Home_State_VT                      bool
Preferred_Attraction_Other         bool
Preferred_Attraction_Thrill        bool
Referral_Source_Friend             bool
Referral_Source_Social Media       bool
Dining_Plan_None                   bool
dtype: object</code></pre>
</div>
</div>
<div id="458900d8-4c7a-49f2-b27c-720a5ded977e" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all bool variables to numeric form</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>train_df <span class="op">=</span> train_df.astype({col: <span class="bu">int</span> <span class="cf">for</span> col <span class="kw">in</span> train_df.select_dtypes(<span class="st">'bool'</span>).columns})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="e572eb9c-786e-4a71-9a05-be2fe861d78e" class="cell" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> train_df.drop(columns<span class="op">=</span>[<span class="st">'Renewed_Pass'</span>])</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> train_df[<span class="st">'Renewed_Pass'</span>]</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> sm.add_constant(X_train)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>logit_model <span class="op">=</span> sm.Logit(y_train, X_train)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>passholder_model <span class="op">=</span> logit_model.fit()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.647964
         Iterations 5</code></pre>
</div>
</div>
</section>
<section id="show-the-summary-of-your-model-with-log_reg.summary." class="level4">
<h4 class="anchored" data-anchor-id="show-the-summary-of-your-model-with-log_reg.summary.">Show the summary of your model with log_reg.summary().</h4>
<div id="3ebac30e-12ed-4d5d-aae8-83f7edbd42c4" class="cell" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>passholder_model.summary()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<table class="simpletable caption-top table table-sm table-striped small">
<caption>Logit Regression Results</caption>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Dep. Variable:</th>
<td>Renewed_Pass</td>
<th data-quarto-table-cell-role="th">No. Observations:</th>
<td>592</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Model:</th>
<td>Logit</td>
<th data-quarto-table-cell-role="th">Df Residuals:</th>
<td>574</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Method:</th>
<td>MLE</td>
<th data-quarto-table-cell-role="th">Df Model:</th>
<td>17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Date:</th>
<td>Mon, 12 Jan 2026</td>
<th data-quarto-table-cell-role="th">Pseudo R-squ.:</th>
<td>0.04379</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Time:</th>
<td>23:40:33</td>
<th data-quarto-table-cell-role="th">Log-Likelihood:</th>
<td>-383.59</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">converged:</th>
<td>True</td>
<th data-quarto-table-cell-role="th">LL-Null:</th>
<td>-401.16</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Covariance Type:</th>
<td>nonrobust</td>
<th data-quarto-table-cell-role="th">LLR p-value:</th>
<td>0.005978</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<td></td>
<th data-quarto-table-cell-role="th">coef</th>
<th data-quarto-table-cell-role="th">std err</th>
<th data-quarto-table-cell-role="th">z</th>
<th data-quarto-table-cell-role="th">P&gt;|z|</th>
<th data-quarto-table-cell-role="th">[0.025</th>
<th data-quarto-table-cell-role="th">0.975]</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">const</th>
<td>0.7841</td>
<td>0.694</td>
<td>1.130</td>
<td>0.258</td>
<td>-0.576</td>
<td>2.144</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Age</th>
<td>-0.0079</td>
<td>0.005</td>
<td>-1.462</td>
<td>0.144</td>
<td>-0.019</td>
<td>0.003</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<td>0.0647</td>
<td>0.041</td>
<td>1.568</td>
<td>0.117</td>
<td>-0.016</td>
<td>0.146</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<td>-0.0004</td>
<td>0.001</td>
<td>-0.411</td>
<td>0.681</td>
<td>-0.002</td>
<td>0.001</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<td>0.1498</td>
<td>0.093</td>
<td>1.618</td>
<td>0.106</td>
<td>-0.032</td>
<td>0.331</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<td>0.0494</td>
<td>0.064</td>
<td>0.769</td>
<td>0.442</td>
<td>-0.076</td>
<td>0.175</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<td>4.514e-05</td>
<td>0.005</td>
<td>0.010</td>
<td>0.992</td>
<td>-0.009</td>
<td>0.009</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<td>0.0031</td>
<td>0.005</td>
<td>0.559</td>
<td>0.576</td>
<td>-0.008</td>
<td>0.014</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Home_State_ME</th>
<td>-0.2888</td>
<td>0.357</td>
<td>-0.810</td>
<td>0.418</td>
<td>-0.988</td>
<td>0.410</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Home_State_NH</th>
<td>-0.1766</td>
<td>0.364</td>
<td>-0.486</td>
<td>0.627</td>
<td>-0.889</td>
<td>0.536</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Home_State_NJ</th>
<td>-1.1599</td>
<td>0.349</td>
<td>-3.322</td>
<td>0.001</td>
<td>-1.844</td>
<td>-0.476</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Home_State_NY</th>
<td>-0.6981</td>
<td>0.329</td>
<td>-2.122</td>
<td>0.034</td>
<td>-1.343</td>
<td>-0.053</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Home_State_VT</th>
<td>-1.0633</td>
<td>0.322</td>
<td>-3.299</td>
<td>0.001</td>
<td>-1.695</td>
<td>-0.432</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Preferred_Attraction_Other</th>
<td>-0.2398</td>
<td>0.239</td>
<td>-1.004</td>
<td>0.315</td>
<td>-0.708</td>
<td>0.228</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Preferred_Attraction_Thrill</th>
<td>-0.5000</td>
<td>0.251</td>
<td>-1.988</td>
<td>0.047</td>
<td>-0.993</td>
<td>-0.007</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Referral_Source_Friend</th>
<td>-0.3234</td>
<td>0.246</td>
<td>-1.313</td>
<td>0.189</td>
<td>-0.806</td>
<td>0.159</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Referral_Source_Social Media</th>
<td>-0.0085</td>
<td>0.221</td>
<td>-0.039</td>
<td>0.969</td>
<td>-0.442</td>
<td>0.425</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Dining_Plan_None</th>
<td>0.0198</td>
<td>0.186</td>
<td>0.106</td>
<td>0.916</td>
<td>-0.346</td>
<td>0.385</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="which-of-your-numeric-variables-here-are-showing-high-p-values" class="level4">
<h4 class="anchored" data-anchor-id="which-of-your-numeric-variables-here-are-showing-high-p-values">Which of your numeric variables here are showing high p-values?</h4>
<p>A p-value greater than 0.05 means the variable is not statistically significant, suggesting that any observed effect could easily be due to random chance rather than a real relationship with renewal behavior. All the numeric variables display relatively high p-values, suggesting that none are statistically significant predictors of renewal at the 0.05 level. Age (p = 0.144), Previous_Visits (p = 0.117), Feedback_Score (p = 0.106), and Distance_From_Park_Miles (p = 0.576) show weak associations with renewal status, while Total_Spend_2024 (p = 0.681) and Email_Engagement_Score (p = 0.992) are particularly uninformative. This indicates that these factors do not have a meaningful impact on predicting renewal behavior.</p>
</section>
<section id="for-your-categorical-variables-which-ones-are-showing-high-p-values-for-all-of-the-levels-in-the-model-summary" class="level4">
<h4 class="anchored" data-anchor-id="for-your-categorical-variables-which-ones-are-showing-high-p-values-for-all-of-the-levels-in-the-model-summary">For your categorical variables, which ones are showing high p-values for ALL of the levels in the model summary?</h4>
<p>For the categorical variables, both Referral_Source and Dining_Plan have high p-values across all levels: Referral_Source_Friend (p = 0.189), Referral_Source_Social Media (p = 0.969), and Dining_Plan_None (p = 0.916) suggesting they are not statistically significant overall.</p>
<p>On the other hand, several Home_State variables are significant, including NJ (p = 0.001), NY (p = 0.034), and VT (p = 0.001), indicating that passholder’s location may impact one’s renewal behavior. Similarly, Preferred_Attraction_Thrill is significant (p = 0.047), implying that customers who prefer thrill rides are less likely to renew compared to those who prefer entertainment attractions. Overall, these results suggest that geographic and experiential factors have stronger predictive power than engagement or spending-related measures.</p>
</section>
</section>
<section id="iteration-2" class="level3">
<h3 class="anchored" data-anchor-id="iteration-2">Iteration #2</h3>
<section id="build-yet-another-model-use-training-set-only." class="level4">
<h4 class="anchored" data-anchor-id="build-yet-another-model-use-training-set-only.">Build yet another model, use training set only.</h4>
<p>For the new model, I’m keeping only the variables that showed a meaningful relationship with renewal in the previous analysis. This includes Home_State (specifically NJ, NY, and VT) and Preferred_Attraction_Thrill, since these had p-values below 0.05 and appear to influence whether a passholder renews.</p>
<p>All other variables are being dropped because they were not statistically significant. This includes all the numeric variables, such as Age, Previous_Visits, Total_Spend_2024, Feedback_Score, Gold_Zone_Visits, Email_Engagement_Score, and Distance_From_Park_Miles, as well as categorical variables: Referral_Source and Dining_Plan.</p>
<div id="749d8049-a336-4e33-b6d9-e22174f0cfa5" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop all insignificant variables for the 2nd model including all numeric variables and some categorical variables</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>drop_vars <span class="op">=</span> [</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Age'</span>, <span class="st">'Previous_Visits'</span>, <span class="st">'Total_Spend_2024'</span>, <span class="st">'Feedback_Score'</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Gold_Zone_Visits'</span>, <span class="st">'Email_Engagement_Score'</span>, <span class="st">'Distance_From_Park_Miles'</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State_ME'</span>, <span class="st">'Home_State_NH'</span>, <span class="st">'Preferred_Attraction_Other'</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Referral_Source_Friend'</span>, <span class="st">'Referral_Source_Social Media'</span>, <span class="st">'Dining_Plan_None'</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> train_df.drop(columns<span class="op">=</span>[<span class="st">'Renewed_Pass'</span>] <span class="op">+</span> drop_vars)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> train_df[<span class="st">'Renewed_Pass'</span>]</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> sm.add_constant(X_train)</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>logit_model <span class="op">=</span> sm.Logit(y_train, X_train)</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>passholder_model2 <span class="op">=</span> logit_model.fit()</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>passholder_model2.summary()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.658103
         Iterations 5</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="29">
<table class="simpletable caption-top table table-sm table-striped small">
<caption>Logit Regression Results</caption>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Dep. Variable:</th>
<td>Renewed_Pass</td>
<th data-quarto-table-cell-role="th">No. Observations:</th>
<td>592</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Model:</th>
<td>Logit</td>
<th data-quarto-table-cell-role="th">Df Residuals:</th>
<td>587</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Method:</th>
<td>MLE</td>
<th data-quarto-table-cell-role="th">Df Model:</th>
<td>4</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Date:</th>
<td>Mon, 12 Jan 2026</td>
<th data-quarto-table-cell-role="th">Pseudo R-squ.:</th>
<td>0.02882</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Time:</th>
<td>23:40:33</td>
<th data-quarto-table-cell-role="th">Log-Likelihood:</th>
<td>-389.60</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">converged:</th>
<td>True</td>
<th data-quarto-table-cell-role="th">LL-Null:</th>
<td>-401.16</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Covariance Type:</th>
<td>nonrobust</td>
<th data-quarto-table-cell-role="th">LLR p-value:</th>
<td>0.0001195</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<td></td>
<th data-quarto-table-cell-role="th">coef</th>
<th data-quarto-table-cell-role="th">std err</th>
<th data-quarto-table-cell-role="th">z</th>
<th data-quarto-table-cell-role="th">P&gt;|z|</th>
<th data-quarto-table-cell-role="th">[0.025</th>
<th data-quarto-table-cell-role="th">0.975]</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">const</th>
<td>0.9015</td>
<td>0.154</td>
<td>5.856</td>
<td>0.000</td>
<td>0.600</td>
<td>1.203</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Home_State_NJ</th>
<td>-0.9522</td>
<td>0.260</td>
<td>-3.659</td>
<td>0.000</td>
<td>-1.462</td>
<td>-0.442</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Home_State_NY</th>
<td>-0.5710</td>
<td>0.230</td>
<td>-2.480</td>
<td>0.013</td>
<td>-1.022</td>
<td>-0.120</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Home_State_VT</th>
<td>-0.8204</td>
<td>0.220</td>
<td>-3.733</td>
<td>0.000</td>
<td>-1.251</td>
<td>-0.390</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Preferred_Attraction_Thrill</th>
<td>-0.2833</td>
<td>0.179</td>
<td>-1.579</td>
<td>0.114</td>
<td>-0.635</td>
<td>0.068</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="using-scikit-learn-build-another-version-of-your-model-using-your-remaining-variables." class="level4">
<h4 class="anchored" data-anchor-id="using-scikit-learn-build-another-version-of-your-model-using-your-remaining-variables.">Using scikit-learn, build another version of your model, using your remaining variables.</h4>
<div id="a2ea5f92-f414-4172-ba9a-95ce99102a0e" class="cell" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> passholder[[<span class="st">'Home_State_NJ'</span>, <span class="st">'Home_State_NY'</span>, <span class="st">'Home_State_VT'</span>, <span class="st">'Preferred_Attraction_Thrill'</span>]]</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> passholder[<span class="st">'Renewed_Pass'</span>]</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">156</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>X_train_scaled <span class="op">=</span> scaler.fit_transform(X_train)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>X_test_scaled <span class="op">=</span> scaler.transform(X_test)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>logmodel <span class="op">=</span> LogisticRegression(max_iter<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>logmodel.fit(X_train_scaled, y_train)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Intercept: </span><span class="sc">{</span>logmodel<span class="sc">.</span>intercept_[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Coefficient:"</span>)</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> feature, coef <span class="kw">in</span> <span class="bu">zip</span>(X_train.columns, logmodel.coef_[<span class="dv">0</span>]):</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>feature<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>coef<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept: 0.370

Coefficient:
Home_State_NJ: -0.325
Home_State_NY: -0.224
Home_State_VT: -0.341
Preferred_Attraction_Thrill: -0.133</code></pre>
</div>
</div>
</section>
<section id="assess-the-performance-of-your-model-against-the-test-set.-build-a-confusion-matrix-and-answer-the-following-questions-about-your-model." class="level4">
<h4 class="anchored" data-anchor-id="assess-the-performance-of-your-model-against-the-test-set.-build-a-confusion-matrix-and-answer-the-following-questions-about-your-model.">Assess the performance of your model against the test set. Build a confusion matrix, and answer the following questions about your model.</h4>
<div id="d3398a8f-9d95-4947-8e1d-ba15cc918036" class="cell" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import metric functions from scikit-learn</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> confusion_matrix, accuracy_score, recall_score, precision_score, balanced_accuracy_score</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> logmodel.predict(X_test_scaled)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>passholder_cm <span class="op">=</span> confusion_matrix(y_test, y_pred)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>tn, fp, fn, tp <span class="op">=</span> confusion_matrix(y_test, y_pred).ravel()</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The model's confusion matrix:</span><span class="ch">\n</span><span class="st">"</span>, passholder_cm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The model's confusion matrix:
 [[ 39 133]
 [ 48 176]]</code></pre>
</div>
</div>
<div id="3654008a-9790-413d-8d12-52071a28e384" class="cell" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>sns.heatmap(passholder_cm, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">'d'</span>, cmap<span class="op">=</span><span class="st">'coolwarm'</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>            xticklabels<span class="op">=</span>[<span class="st">'Actual 1'</span>, <span class="st">'Actual 0'</span>],</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>            yticklabels<span class="op">=</span>[<span class="st">'Predict 1'</span>, <span class="st">'Predict 0'</span>])</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Actual Label"</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Predicted Label"</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Confusion Matrix"</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="classification_files/figure-html/cell-33-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The model correctly predicted 39 as non‑renewal (TN) and incorrectly predicted as 133 renewal (FP). While it correctly predicted 176 as renewal (TP) and incorrectly predicted 48 as non‑renewal (FN).</p>
</section>
<section id="what-is-your-models-accuracy-rate" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-accuracy-rate">What is your model’s accuracy rate?</h4>
<div id="522b82ed-fdbd-4e23-9223-223c8bfbdc65" class="cell" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> accuracy_score(y_test, y_pred)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy Rate: </span><span class="sc">{</span>accuracy<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy Rate: 0.543</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-sensitivity-rate" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-sensitivity-rate">What is your model’s sensitivity rate?</h4>
<div id="aaa61ef9-27fd-4621-b9e3-ec38d2f6abdd" class="cell" data-execution_count="34">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="op">=</span> recall_score(y_test, y_pred)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sensitivity Rate: </span><span class="sc">{</span>sensitivity<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sensitivity Rate: 0.786</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-specificity-rate" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-specificity-rate">What is your model’s specificity rate?</h4>
<div id="1cb78122-d6bb-4cdb-81c9-05ec66e47093" class="cell" data-execution_count="35">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>specificity <span class="op">=</span> tn <span class="op">/</span> (tn <span class="op">+</span> fp)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Specificity Rate: </span><span class="sc">{</span>specificity<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Specificity Rate: 0.227</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-precision" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-precision">What is your model’s precision?</h4>
<div id="06d435a8-02ca-420e-be05-935ff329997f" class="cell" data-execution_count="36">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>precision <span class="op">=</span> precision_score(y_test, y_pred)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Precision: </span><span class="sc">{</span>precision<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision: 0.570</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-balanced-accuracy" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-balanced-accuracy">What is your model’s balanced accuracy?</h4>
<div id="dc75a01c-c669-42fa-96b2-71fbd68b68ea" class="cell" data-execution_count="37">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>balanced_accuracy <span class="op">=</span> balanced_accuracy_score(y_test, y_pred)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Balanced Accuracy: </span><span class="sc">{</span>balanced_accuracy<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Balanced Accuracy: 0.506</code></pre>
</div>
</div>
<p>The model shows good sensitivity (0.786), meaning it captures most renewals, but low specificity (0.227), missing many non-renewals. With overall accuracy at 54.3%, which is slightly above baseline, suggesting that it leans toward predicting renewals and struggles to distinguish non-renewals effectively.</p>
</section>
<section id="what-is-the-naive-accuracy-rate-baseline-rate-for-this-dataset" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-naive-accuracy-rate-baseline-rate-for-this-dataset">What is the naive accuracy rate (baseline rate) for this dataset?</h4>
<div id="37f9f838-2c56-454f-9bc8-e22a60c1c39e" class="cell" data-execution_count="38">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>baseline_rate <span class="op">=</span> <span class="bu">max</span>(y_test.mean(), <span class="dv">1</span> <span class="op">-</span> y_test.mean())</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Naive Accuracy Rate: </span><span class="sc">{</span>baseline_rate<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Naive Accuracy Rate: 0.566</code></pre>
</div>
</div>
</section>
<section id="how-does-this-compare-with-your-models-accuracy-rate-if-a-classification-models-accuracy-is-not-much-better-than-the-naive-rate-can-the-model-still-be-useful-if-so-how" class="level4">
<h4 class="anchored" data-anchor-id="how-does-this-compare-with-your-models-accuracy-rate-if-a-classification-models-accuracy-is-not-much-better-than-the-naive-rate-can-the-model-still-be-useful-if-so-how">How does this compare with your model’s accuracy rate? If a classification model’s accuracy is not much better than the naive rate, can the model still be useful? If so, how?</h4>
<p>My model achieved an accuracy of 54.3%, which is slightly lower than the naive baseline rate of 56.6%, representing the proportion of the majority class. Although it didn’t outperform a simple majority prediction, accuracy alone doesn’t capture the model’s full value. The model can still be useful if it improves metrics like sensitivity or precision, especially when correctly identifying renewals would help with targeted marketing and better allocation.</p>
</section>
<section id="compare-your-models-accuracy-against-the-training-set-vs.-accuracy-against-the-test-set." class="level4">
<h4 class="anchored" data-anchor-id="compare-your-models-accuracy-against-the-training-set-vs.-accuracy-against-the-test-set.">Compare your model’s accuracy against the training set vs.&nbsp;accuracy against the test set.</h4>
<div id="17358407-a3ac-4126-a178-7e0b72ae6a76" class="cell" data-execution_count="39">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy score for trained dataset</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>train_pred <span class="op">=</span> logmodel.predict(X_train_scaled)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>train_acc <span class="op">=</span> accuracy_score(y_train, train_pred)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy score for tested dataset</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>test_pred <span class="op">=</span> logmodel.predict(X_test_scaled)</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>test_acc <span class="op">=</span> accuracy_score(y_test, test_pred)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy score for training set: </span><span class="sc">{</span>train_acc<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy score for test set: </span><span class="sc">{</span>test_acc<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy score for training set: 0.610
Accuracy score for test set: 0.543</code></pre>
</div>
</div>
</section>
<section id="what-is-the-purpose-of-comparing-those-two-values" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-purpose-of-comparing-those-two-values">What is the purpose of comparing those two values?</h4>
<p>Comparing the training and test accuracy helps determine how well the model performs on new data. When there is a large difference between the two values, it often means the model is overfitting, whereas the model is doing well on the training data but struggling to generalize. A smaller difference usually means the model is more consistent and better at handling unseen data.</p>
</section>
<section id="in-this-case-what-does-the-comparison-of-those-values-suggest-about-the-model-that-you-have-built" class="level4">
<h4 class="anchored" data-anchor-id="in-this-case-what-does-the-comparison-of-those-values-suggest-about-the-model-that-you-have-built">In this case, what does the comparison of those values suggest about the model that you have built?</h4>
<p>In this case, the training accuracy (61.0%) is only slightly higher than the test accuracy (54.3%), so overfitting is not the main concern. However, both accuracy rates are relatively low and close to the naive baseline, which could indicate that the model is underfitting or that the chosen variables don’t provide enough predictive evidence. Additional data or more informative features might be needed to increase the model’s efficiency.</p>
</section>
<section id="make-up-a-passholder.-assign-this-customer-a-value-for-each-predictor-variable-in-this-model-and-store-the-results-in-a-new-dataframe." class="level4">
<h4 class="anchored" data-anchor-id="make-up-a-passholder.-assign-this-customer-a-value-for-each-predictor-variable-in-this-model-and-store-the-results-in-a-new-dataframe.">Make up a passholder. Assign this customer a value for each predictor variable in this model, and store the results in a new dataframe.</h4>
<div id="49547288-8f3d-4c11-851d-e1f9d65df334" class="cell" data-execution_count="40">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample passholder A who's from NY and preferred thrill attraction</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>passholder_A <span class="op">=</span> pd.DataFrame([{</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State_NJ'</span>: <span class="dv">0</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State_NY'</span>: <span class="dv">1</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State_VT'</span>: <span class="dv">0</span>,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Preferred_Attraction_Thrill'</span>: <span class="dv">1</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>}])</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale using previously fitted scaler</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>passholder_A_scaled <span class="op">=</span> scaler.transform(passholder_A)</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict renewal probability</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>passholder_A_prob <span class="op">=</span> logmodel.predict_proba(passholder_A_scaled)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>passholder_A_class <span class="op">=</span> logmodel.predict(passholder_A_scaled)[<span class="dv">0</span>]</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Class for Passholder A: </span><span class="sc">{</span>passholder_A_class<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Renewal Probability for Passholder A: </span><span class="sc">{</span>passholder_A_prob<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Class for Passholder A: 1
Predicted Renewal Probability for Passholder A: 0.513</code></pre>
</div>
</div>
</section>
<section id="what-did-your-model-predict-will-this-passholder-renew" class="level4">
<h4 class="anchored" data-anchor-id="what-did-your-model-predict-will-this-passholder-renew">What did your model predict – will this passholder renew?</h4>
<p>To test the model, I created Passholder A, who is from New York (NY) and prefers Thrill Attractions. Based on the model’s prediction, Passholder A falls into class 1, meaning they are expected to renew their pass at Lobster Land.</p>
</section>
<section id="according-to-your-model-what-is-the-probability-that-the-passholder-will-renew" class="level4">
<h4 class="anchored" data-anchor-id="according-to-your-model-what-is-the-probability-that-the-passholder-will-renew">According to your model, what is the probability that the passholder will renew?</h4>
<p>According to the model, the predicted probability of renewal for Passholder A is 51.3%, indicating that while there is some likelihood of non-renewal, it is above the 50% threshold used for classifying renewers.</p>
</section>
<section id="when-using-a-logistic-regression-model-to-make-predictions-why-is-it-important-to-only-use-values-within-the-range-of-the-dataset-used-to-build-the-model" class="level4">
<h4 class="anchored" data-anchor-id="when-using-a-logistic-regression-model-to-make-predictions-why-is-it-important-to-only-use-values-within-the-range-of-the-dataset-used-to-build-the-model">When using a logistic regression model to make predictions, why is it important to only use values within the range of the dataset used to build the model?</h4>
</section>
<section id="make-a-new-dataframe-but-this-time-for-the-numeric-predictor-variables-select-some-numbers-that-are-outside-the-range-of-the-dataset.-use-your-model-to-make-a-prediction-for-this-new-dataframe." class="level4">
<h4 class="anchored" data-anchor-id="make-a-new-dataframe-but-this-time-for-the-numeric-predictor-variables-select-some-numbers-that-are-outside-the-range-of-the-dataset.-use-your-model-to-make-a-prediction-for-this-new-dataframe.">Make a new dataframe, but this time, for the numeric predictor variables, select some numbers that are outside the range of the dataset. Use your model to make a prediction for this new dataframe.</h4>
<div id="767700bb-a3d4-4bbd-a9fb-c1b0d768ab16" class="cell" data-execution_count="41">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create unrealistic but structurally valid input for passholder Z</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>passholder_Z <span class="op">=</span> pd.DataFrame([{</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State_NJ'</span>: <span class="dv">0</span>,</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State_NY'</span>: <span class="dv">1</span>,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State_VT'</span>: <span class="dv">0</span>,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Preferred_Attraction_Thrill'</span>: <span class="dv">999</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>}])</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>passholder_Z_scaled <span class="op">=</span> scaler.transform(passholder_Z)</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>passholder_Z_prob <span class="op">=</span> logmodel.predict_proba(passholder_Z_scaled)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>passholder_Z_class <span class="op">=</span> logmodel.predict(passholder_Z_scaled)[<span class="dv">0</span>]</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Class for Passholder Z: </span><span class="sc">{</span>passholder_Z_class<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Probability for Passholder Z: </span><span class="sc">{</span>passholder_Z_prob<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Class for Passholder Z: 0
Predicted Probability for Passholder Z: 0.000</code></pre>
</div>
</div>
</section>
<section id="what-do-you-notice-about-the-result" class="level4">
<h4 class="anchored" data-anchor-id="what-do-you-notice-about-the-result">What do you notice about the result?</h4>
<p>To test the model, I created Passholder Z from New York (NY) who prefers Thrill Attractions, but assigned an unrealistic value of 999 for Thrill preference, far beyond the training range. Logistic regression handles extreme values by pushing the log-odds sharply, which makes the predicted probability collapse to 0 or 1. As a result, the model predicted a renewal probability of 0.000 and classified this passholder as class 0, demonstrating why input values need to remain within realistic ranges for reliable predictions.</p>
</section>
</section>
</section>
<section id="part-ii-random-forest-model" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-random-forest-model">Part II: Random Forest Model</h2>
<section id="read-the-dataset-back-into-python" class="level4">
<h4 class="anchored" data-anchor-id="read-the-dataset-back-into-python">Read the dataset back into Python</h4>
<div id="0f60ca5e-35e6-4d6e-98e0-a3ab752b5293" class="cell" data-execution_count="42">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>passholder_rf <span class="op">=</span> pd.read_csv(<span class="st">"data/lobsterland_passholders_dataset_25.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="bf3de265-299d-447a-82b0-951106793065" class="cell" data-execution_count="43">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the variables to the categorical data type</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>passholder_rf[[<span class="st">'Home_State'</span>, <span class="st">'Preferred_Attraction'</span>, <span class="st">'Referral_Source'</span>, <span class="st">'Dining_Plan'</span>]] <span class="op">=</span> passholder_rf[[<span class="st">'Home_State'</span>, <span class="st">'Preferred_Attraction'</span>, <span class="st">'Referral_Source'</span>, <span class="st">'Dining_Plan'</span>]].astype(<span class="st">'category'</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Add category 'None' to 'Dining_Plan' variable then fill any NaN values with 'None'</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>passholder_rf[<span class="st">'Dining_Plan'</span>] <span class="op">=</span> passholder_rf[<span class="st">'Dining_Plan'</span>].cat.add_categories([<span class="st">'None'</span>]).fillna(<span class="st">'None'</span>)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the negative Total_Spend_2024 value by filtering it to be greater than 0</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>passholder_rf <span class="op">=</span> passholder_rf[passholder_rf[<span class="st">'Total_Spend_2024'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>]</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Cap Email_Engagement_Score at 100 for those exceeding the 100 range</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>passholder_rf[<span class="st">'Email_Engagement_Score'</span>] <span class="op">=</span> passholder_rf[<span class="st">'Email_Engagement_Score'</span>].clip(upper<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the negative Email_Engagement_Score value by filtering it to be greater than 0</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>passholder_rf <span class="op">=</span> passholder_rf[passholder_rf[<span class="st">'Email_Engagement_Score'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="dummify-the-categorical-inputs-again-but-this-time-dont-drop-any-levels." class="level4">
<h4 class="anchored" data-anchor-id="dummify-the-categorical-inputs-again-but-this-time-dont-drop-any-levels.">Dummify the categorical inputs again, but this time, don’t drop any levels.</h4>
<div id="07b14e94-b0ef-460c-84be-ad6cac81f69b" class="cell" data-execution_count="44">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dummify all categorical variables and no drop</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>passholder_rf <span class="op">=</span> pd.get_dummies(passholder_rf, columns<span class="op">=</span>[</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Home_State'</span>,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Preferred_Attraction'</span>,</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Referral_Source'</span>,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Dining_Plan'</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>], drop_first<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>passholder_rf.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Previous_Visits</th>
<th data-quarto-table-cell-role="th">Total_Spend_2024</th>
<th data-quarto-table-cell-role="th">Feedback_Score</th>
<th data-quarto-table-cell-role="th">Gold_Zone_Visits</th>
<th data-quarto-table-cell-role="th">Email_Engagement_Score</th>
<th data-quarto-table-cell-role="th">Distance_From_Park_Miles</th>
<th data-quarto-table-cell-role="th">Renewed_Pass</th>
<th data-quarto-table-cell-role="th">Home_State_MA</th>
<th data-quarto-table-cell-role="th">Home_State_ME</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Home_State_NY</th>
<th data-quarto-table-cell-role="th">Home_State_VT</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Entertainment</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Other</th>
<th data-quarto-table-cell-role="th">Preferred_Attraction_Thrill</th>
<th data-quarto-table-cell-role="th">Referral_Source_Ad/Other</th>
<th data-quarto-table-cell-role="th">Referral_Source_Friend</th>
<th data-quarto-table-cell-role="th">Referral_Source_Social Media</th>
<th data-quarto-table-cell-role="th">Dining_Plan_Upgraded</th>
<th data-quarto-table-cell-role="th">Dining_Plan_None</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>59.000000</td>
<td>3.000000</td>
<td>394.780000</td>
<td>4.606232</td>
<td>4.000000</td>
<td>44.200000</td>
<td>1.900000</td>
<td>0</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>27.846318</td>
<td>1.064843</td>
<td>172.541334</td>
<td>2.102264</td>
<td>2.000819</td>
<td>37.103840</td>
<td>21.709631</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>18.000000</td>
<td>5.926144</td>
<td>151.731274</td>
<td>3.365074</td>
<td>1.019084</td>
<td>61.827722</td>
<td>21.892411</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>25.000000</td>
<td>12.000000</td>
<td>251.300000</td>
<td>3.458663</td>
<td>1.000000</td>
<td>41.800000</td>
<td>6.600000</td>
<td>0</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>66.206178</td>
<td>4.038141</td>
<td>197.686695</td>
<td>2.985864</td>
<td>3.955755</td>
<td>61.174332</td>
<td>29.981959</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>5 rows × 22 columns</p>
</div>
</div>
</div>
</section>
<section id="re-partition-the-data-using-the-same-seed-value-that-you-used-in-the-previous-part-of-this-assignment." class="level4">
<h4 class="anchored" data-anchor-id="re-partition-the-data-using-the-same-seed-value-that-you-used-in-the-previous-part-of-this-assignment.">Re-partition the data, using the same seed value that you used in the previous part of this assignment.</h4>
<div id="9ead70f9-f597-4f88-8fbc-6c5e6ba07d05" class="cell" data-execution_count="45">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>train_df, test_df <span class="op">=</span> train_test_split(passholder_rf, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">156</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training set size: </span><span class="sc">{</span><span class="bu">len</span>(train_df)<span class="sc">}</span><span class="ss"> rows"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test set size: </span><span class="sc">{</span><span class="bu">len</span>(test_df)<span class="sc">}</span><span class="ss"> rows"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training set size: 592 rows
Test set size: 396 rows</code></pre>
</div>
</div>
</section>
<section id="build-a-random-forest-model-in-python-with-your-training-set-the-only-difference-here-is-that-the-categories-should-not-have-any-levels-dropped.-use-gridsearchcv-to-help-you-determine-the-best-hyperparameter-settings-for-your-model." class="level4">
<h4 class="anchored" data-anchor-id="build-a-random-forest-model-in-python-with-your-training-set-the-only-difference-here-is-that-the-categories-should-not-have-any-levels-dropped.-use-gridsearchcv-to-help-you-determine-the-best-hyperparameter-settings-for-your-model.">Build a random forest model in Python with your training set (the only difference here is that the categories should not have any levels dropped). Use GridSearchCV to help you determine the best hyperparameter settings for your model.</h4>
<div id="82db7545-598c-4eaa-8df0-c2ccf779de30" class="cell" data-execution_count="46">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> GridSearchCV</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>X_rf <span class="op">=</span> passholder_rf.drop(<span class="st">'Renewed_Pass'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>y_rf <span class="op">=</span> passholder_rf[<span class="st">'Renewed_Pass'</span>]</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>X_train_rf, X_test_rf, y_train_rf, y_test_rf <span class="op">=</span> train_test_split(</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>    X_rf, y_rf, test_size<span class="op">=</span><span class="fl">0.4</span>, random_state<span class="op">=</span><span class="dv">156</span></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="007565b0-af18-4a4b-90f1-b04827ac57e1" class="cell" data-execution_count="47">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up a parameter grid for hyperparameter tuning.</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_estimators'</span>: [<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">150</span>],</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_depth'</span>: [<span class="va">None</span>, <span class="dv">5</span>, <span class="dv">10</span>],</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_samples_split'</span>: [<span class="dv">2</span>, <span class="dv">5</span>],</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_samples_leaf'</span>: [<span class="dv">1</span>, <span class="dv">2</span>]}</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate the Random Forest classifier with a fixed random state.</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestClassifier(random_state<span class="op">=</span><span class="dv">156</span>)</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Use GridSearchCV for hyperparameter tuning with 5-fold cross-validation.</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>gridsearch_rf <span class="op">=</span> GridSearchCV(estimator<span class="op">=</span>rf, param_grid<span class="op">=</span>param_grid, cv<span class="op">=</span><span class="dv">5</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>, verbose<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a>gridsearch_rf.fit(X_train_rf, y_train_rf)</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Best parameters found:"</span>, gridsearch_rf.best_params_)</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a>bestparam_rf <span class="op">=</span> gridsearch_rf.best_estimator_</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best parameters found: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 50}</code></pre>
</div>
</div>
</section>
<section id="how-did-your-random-forest-model-rank-the-variables-in-order-of-importance-from-highest-to-lowest" class="level4">
<h4 class="anchored" data-anchor-id="how-did-your-random-forest-model-rank-the-variables-in-order-of-importance-from-highest-to-lowest">How did your random forest model rank the variables in order of importance, from highest to lowest?</h4>
<div id="5c236c1d-cf15-45de-baa7-0ad727227132" class="cell" data-execution_count="48">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract feature importances from the best random forest model</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>importances_rf <span class="op">=</span> bestparam_rf.feature_importances_</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>features_rf <span class="op">=</span> X_train_rf.columns</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>importance_df <span class="op">=</span> pd.DataFrame({<span class="st">'Feature'</span>: features_rf, <span class="st">'Importance'</span>: importances_rf})</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>importance_df <span class="op">=</span> importance_df.sort_values(by<span class="op">=</span><span class="st">'Importance'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Random Forest feature importances ranked from highest to lowest:"</span>)</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>importance_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest feature importances ranked from highest to lowest:</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="48">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Feature</th>
<th data-quarto-table-cell-role="th">Importance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Distance_From_Park_Miles</td>
<td>0.134086</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Feedback_Score</td>
<td>0.126785</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Age</td>
<td>0.123248</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Email_Engagement_Score</td>
<td>0.122290</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Total_Spend_2024</td>
<td>0.116996</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Previous_Visits</td>
<td>0.099605</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Gold_Zone_Visits</td>
<td>0.096552</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">10</th>
<td>Home_State_NJ</td>
<td>0.016589</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>Preferred_Attraction_Other</td>
<td>0.015116</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">12</th>
<td>Home_State_VT</td>
<td>0.015014</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>Home_State_MA</td>
<td>0.014658</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">16</th>
<td>Referral_Source_Ad/Other</td>
<td>0.014174</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">13</th>
<td>Preferred_Attraction_Entertainment</td>
<td>0.013437</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>Preferred_Attraction_Thrill</td>
<td>0.013159</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>Home_State_NH</td>
<td>0.013115</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">18</th>
<td>Referral_Source_Social Media</td>
<td>0.012260</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Home_State_ME</td>
<td>0.011718</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>Dining_Plan_Upgraded</td>
<td>0.010869</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">17</th>
<td>Referral_Source_Friend</td>
<td>0.010784</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>Dining_Plan_None</td>
<td>0.009866</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">11</th>
<td>Home_State_NY</td>
<td>0.009680</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="for-a-random-forest-model-how-can-you-interpret-feature-importance" class="level4">
<h4 class="anchored" data-anchor-id="for-a-random-forest-model-how-can-you-interpret-feature-importance">For a random forest model, how can you interpret feature importance?</h4>
<p>The random forest model ranked variables by how much they reduced classification error across all trees. The top predictors were Distance_From_Park_Miles (0.134), Feedback_Score (0.127), Age (0.123), Email_Engagement_Score (0.122), and Total_Spend_2024 (0.117), while categorical factors like Home_State and Preferred_Attraction had much lower importance (around 0.01–0.02).</p>
<p>Unlike logistic regression, which shows the direction of relationships, random forest feature importance only measures how strongly each variable contributes to predictions. For Lobster Land, this means focusing on key behavioral drivers such as engagement and spending will likely have the greatest impact on improving renewal rates, while factors such as Home_State or Preferred_Attraction appear to play a much smaller role.</p>
</section>
<section id="assess-the-performance-of-your-model-against-the-test-set-using-confusion-matrix-to-do-this." class="level4">
<h4 class="anchored" data-anchor-id="assess-the-performance-of-your-model-against-the-test-set-using-confusion-matrix-to-do-this.">Assess the performance of your model against the test set using confusion matrix to do this.</h4>
<div id="ef5e912e-42f3-4d57-aefa-6761fc6905e3" class="cell" data-execution_count="49">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict outcomes for the Random Forest test set using the best Random Forest model</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>y_pred_rf <span class="op">=</span> bestparam_rf.predict(X_test_rf)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>passholder_cm_rf <span class="op">=</span> confusion_matrix(y_test_rf, y_pred_rf)</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>tn, fp, fn, tp <span class="op">=</span> confusion_matrix(y_test_rf, y_pred_rf).ravel()</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The model's confusion matrix:</span><span class="ch">\n</span><span class="st">"</span>, passholder_cm_rf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The model's confusion matrix:
 [[ 55 117]
 [ 62 162]]</code></pre>
</div>
</div>
<div id="7384b966-b5f4-4542-8ee3-7641c6137be8" class="cell" data-execution_count="50">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>sns.heatmap(passholder_cm_rf, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">'d'</span>, cmap<span class="op">=</span><span class="st">'BuGn'</span>,</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>            xticklabels<span class="op">=</span>[<span class="st">'Actual 1'</span>, <span class="st">'Actual 0'</span>],</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>            yticklabels<span class="op">=</span>[<span class="st">'Predict 1'</span>, <span class="st">'Predict 0'</span>])</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Actual Label"</span>)</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Predicted Label"</span>)</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Random Forest Confusion Matrix"</span>)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="classification_files/figure-html/cell-51-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-is-your-model-s-accuracy-rate" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-model-s-accuracy-rate">What is your model’ s accuracy rate?</h4>
<div id="cb856088-3895-423e-ae61-049a724f9fe7" class="cell" data-execution_count="51">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>accuracy_rf <span class="op">=</span> accuracy_score(y_test_rf, y_pred_rf)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Random Forest Accuracy Rate: </span><span class="sc">{</span>accuracy_rf<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Accuracy Rate: 0.548</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-sensitivity-rate-1" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-sensitivity-rate-1">What is your model’s sensitivity rate?</h4>
<div id="1dcd1653-0478-4677-adac-9ee776c4caba" class="cell" data-execution_count="52">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>sensitivity_rf <span class="op">=</span> recall_score(y_test_rf, y_pred_rf)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Random Forest Sensitivity Rate: </span><span class="sc">{</span>sensitivity_rf<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Sensitivity Rate: 0.723</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-specificity-rate-1" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-specificity-rate-1">What is your model’s specificity rate?</h4>
<div id="aad0b65e-a431-404d-9188-269c680a1d6a" class="cell" data-execution_count="53">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>specificity_rf <span class="op">=</span> tn <span class="op">/</span> (tn <span class="op">+</span> fp)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Random Forest Specificity Rate: </span><span class="sc">{</span>specificity_rf<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Specificity Rate: 0.320</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-precision-1" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-precision-1">What is your model’s precision?</h4>
<div id="0b2577c3-d2c1-41b6-b343-badd00a8d021" class="cell" data-execution_count="54">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>precision_rf <span class="op">=</span> precision_score(y_test_rf, y_pred_rf)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Random Forest Precision: </span><span class="sc">{</span>precision_rf<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Precision: 0.581</code></pre>
</div>
</div>
</section>
<section id="what-is-your-models-balanced-accuracy-1" class="level4">
<h4 class="anchored" data-anchor-id="what-is-your-models-balanced-accuracy-1">What is your model’s balanced accuracy?</h4>
<div id="71710847-bd0f-43dc-9772-1d163b56463e" class="cell" data-execution_count="55">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>balanced_accuracy_rf <span class="op">=</span> balanced_accuracy_score(y_test_rf, y_pred_rf)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Random Forest Balanced Accuracy: </span><span class="sc">{</span>balanced_accuracy_rf<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Balanced Accuracy: 0.521</code></pre>
</div>
</div>
</section>
<section id="compare-your-models-accuracy-against-the-training-set-vs.-your-models-accuracy-against-the-test-set." class="level4">
<h4 class="anchored" data-anchor-id="compare-your-models-accuracy-against-the-training-set-vs.-your-models-accuracy-against-the-test-set.">Compare your model’s accuracy against the training set vs.&nbsp;your model’s accuracy against the test set.</h4>
<div id="32298ad6-8774-4b12-bc2d-b45954e845f7" class="cell" data-execution_count="56">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy score for RF trained dataset</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>train_pred_rf <span class="op">=</span> bestparam_rf.predict(X_train_rf)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>train_acc_rf <span class="op">=</span> accuracy_score(y_train_rf, train_pred)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy score for RF tested dataset</span></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>test_pred_rf <span class="op">=</span> bestparam_rf.predict(X_test_rf)</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>test_acc_rf <span class="op">=</span> accuracy_score(y_test_rf, test_pred)</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy score for Random Forest training set: </span><span class="sc">{</span>train_acc_rf<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy score for Random Forest test set: </span><span class="sc">{</span>test_acc_rf<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy score for Random Forest training set: 0.610
Accuracy score for Random Forest test set: 0.543</code></pre>
</div>
</div>
</section>
<section id="how-different-were-these-results" class="level4">
<h4 class="anchored" data-anchor-id="how-different-were-these-results">How different were these results?</h4>
<p>The random forest model performed slightly better on the training data (61.0%) than on the test data (54.3%), showing a modest gap of about 6.7 percentage points. The small gap suggests the Random Forest isn’t overfitting but may have limited generalization, likely because the features don’t fully explain renewal behavior or key factors are missing from the data.</p>
</section>
<section id="use-the-predict-function-with-your-model-to-classify-the-person-who-you-invented-in-the-previous-section." class="level4">
<h4 class="anchored" data-anchor-id="use-the-predict-function-with-your-model-to-classify-the-person-who-you-invented-in-the-previous-section.">Use the predict() function with your model to classify the person who you invented in the previous section.</h4>
<div id="197dea1a-867c-43a6-9820-18d6a33fdfdc" class="cell" data-execution_count="57">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Start with a template row of zeros for then update with selected features</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>passholder_A <span class="op">=</span> pd.DataFrame([<span class="bu">dict</span>.fromkeys(X_train_rf.columns, <span class="dv">0</span>)])</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>passholder_A[<span class="st">'Home_State_NY'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>passholder_A[<span class="st">'Preferred_Attraction_Thrill'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>pred_class <span class="op">=</span> bestparam_rf.predict(passholder_A)[<span class="dv">0</span>]</span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>pred_prob <span class="op">=</span> bestparam_rf.predict_proba(passholder_A)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Class for Passholder A (Random Forest): </span><span class="sc">{</span>pred_class<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Renewal Probability (Random Forest): </span><span class="sc">{</span>pred_prob<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Class for Passholder A (Random Forest): 1
Predicted Renewal Probability (Random Forest): 0.504</code></pre>
</div>
</div>
</section>
<section id="does-the-model-think-that-the-passholder-will-renew" class="level4">
<h4 class="anchored" data-anchor-id="does-the-model-think-that-the-passholder-will-renew">Does the model think that the passholder will renew?</h4>
<p>The Random Forest model predicts that Passholder A will renew (class 1) with a renewal probability of 50.4%, though this suggests a moderate likelihood of renewing their pass.</p>
<p>Lobster Land can use these models as practical tools to identify which passholders are more or less likely to renew, focusing on the variables that stood out in both analyses. The logistic regression pointed to factors like Home_State and Preferred_Attraction types, suggesting opportunities for local/geographical or interest-based marketing. The random forest, on the other hand, added further insights by focusing on behavioral and engagement factors: Distance_From_Park_Miles, Feedback_Score, Total_Spending_2024, and Previous_Visits as key drivers of renewal.</p>
<p>By combining these insights, Lobster Land can target passholders who live farther away, show lower satisfaction, or engage less often, while rewarding loyal visitors. For instance, the park could offer transportation discounts, personalized follow-ups, or loyalty perks to strengthen renewal intent and use its marketing resources more effectively.</p>
</section>
</section>
<section id="part-iii-tableau-dashboard" class="level2">
<h2 class="anchored" data-anchor-id="part-iii-tableau-dashboard">Part III: Tableau Dashboard</h2>
<p>Here’s the public link for my dashboard: https://public.tableau.com/app/profile/nhat.tran5503/viz/LobsterLandKPIDashBoard2025/Dashboard1?publish=yes</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="classification_files/figure-html/7179d0d4-2e53-41ca-b545-190993b50565-1-540a0810-b23b-4d62-9961-3e465912dd11.png" class="img-fluid figure-img"></p>
<figcaption>image.png</figcaption>
</figure>
</div>
<p>The Lobster Land KPI Dashboard reveals patterns and trends that help management understand park performance and make informed decisions. It shows which days see the most visitors, how weather impacts ticket sales, and which attractions and seasons generate the most revenue. By tracking these metrics, management can also see whether the park is meeting its KPIs, such as visitor targets, revenue goals, and event performance, and use the insights to adjust staffing, marketing, and resources as needed.</p>
<ul>
<li><p><strong>Average Visitors by Day of the Week (Line Chart):</strong> This chart shows how attendance varies across the week, with weekends (Friday–Saturday) drawing the highest visitor counts. It helps identify peak days for staffing and promotions.</p></li>
<li><p><strong>Day Tickets Sold by Weather Type (Box Plot):</strong> The box plots compare ticket sales under different weather conditions, revealing how sunny days show the highest ticket sales, while rainy or stormy conditions lead to fewer visitors, highlighting the strong influence of weather on attendance.</p></li>
<li><p><strong>Total Revenue by Attraction Tiers (Pie Chart):</strong> The pie chart highlights how Tier 1 generate the largest share of revenue compared to Tier 2 and Tier 3. This emphasizes the importance of maintaining and marketing top-tier experiences.</p></li>
<li><p><strong>Revenue Breakdown by Season (Bar Chart):</strong> Seasonal bars show how revenue streams (food, merchandise, events) shift across seasons. Summer produces the strongest revenue across categories, especially in food and merchandise, reflecting peak tourism and vacation travel.This helps Lobster Land plan seasonal offerings and optimize resource allocation.</p></li>
<li><p><strong>International Visitors and Merch Revenue During Special Events (Combination of Bar + Line Chart):</strong> This chart compares per‑capita spending and merchandise revenue across major events, showing which events drive the most international engagement and sales. It helps prioritize which events to expand or replicate.</p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/nhattran309\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>