<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Market Segmentation &amp; Conjoint Analysis – Nhat Tran</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1db3f541d99483cdc7a0d9cf38862b2c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nhat Tran</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-academics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Academics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-academics">    
        <li>
    <a class="dropdown-item" href="../coursework.html">
 <span class="dropdown-text">Relevant Coursework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../pynotes.html">
 <span class="dropdown-text">Python Notebooks</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../certifications.html"> 
<span class="menu-text">Certifications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-i-segmentation" id="toc-part-i-segmentation" class="nav-link active" data-scroll-target="#part-i-segmentation">Part I: Segmentation</a></li>
  <li><a href="#part-ii-conjoint-analysis-with-a-linear-model" id="toc-part-ii-conjoint-analysis-with-a-linear-model" class="nav-link" data-scroll-target="#part-ii-conjoint-analysis-with-a-linear-model">Part II: Conjoint Analysis with a Linear Model</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Market Segmentation &amp; Conjoint Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Analyzed Lobster Land’s operations using k-means clustering to segment park days based on attendance, pricing, weather, and spending behavior, uncovering distinct day types to inform staffing, pricing, and marketing decisions. Conducted a conjoint analysis with a linear regression model to quantify how entertainment features, crowding, and experience design impact guest satisfaction, translating insights into actionable recommendations for revenue and experience optimization.</p>
<div id="c9ca770b-32ec-48c6-873d-1cc76867942d" class="cell" data-execution_count="78">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> KMeans</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="part-i-segmentation" class="level2">
<h2 class="anchored" data-anchor-id="part-i-segmentation">Part I: Segmentation</h2>
<div id="ad418274-2ee0-478c-ad8a-81e14e1be166" class="cell" data-execution_count="79">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import day_25.csv files into python for use</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>day_25 <span class="op">=</span> pd.read_csv(<span class="st">"data/days25.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="0964cf49-9956-4fb7-a169-299cfe918043" class="cell" data-execution_count="80">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Then use info() and head() function to show how the data is stored</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>day_25.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 99 entries, 0 to 98
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Day_ID                  99 non-null     int64  
 1   Day_of_Week             99 non-null     object 
 2   season_week_rel         99 non-null     int64  
 3   Is_Holiday              99 non-null     int64  
 4   Total_Visitors          99 non-null     int64  
 5   Passholder_Percentage   99 non-null     float64
 6   Day_Tickets_Sold        99 non-null     int64  
 7   Avg_Ticket_Price        99 non-null     float64
 8   Gate_Revenue            99 non-null     float64
 9   Revenue_Food            99 non-null     float64
 10  Revenue_Merch           99 non-null     float64
 11  Revenue_Arcade          99 non-null     float64
 12  Total_Revenue           99 non-null     float64
 13  Total_Labor_Hours       99 non-null     float64
 14  International_Visitors  99 non-null     float64
 15  High_Temperature        99 non-null     float64
 16  Weather_Type            99 non-null     object 
 17  Is_Special_Event        99 non-null     int64  
 18  Per_Capita_Spend        99 non-null     float64
dtypes: float64(11), int64(6), object(2)
memory usage: 14.8+ KB</code></pre>
</div>
</div>
<div id="93f6cd73-0daa-41cb-9248-3fe07434ff16" class="cell" data-execution_count="81">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>day_25.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="81">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Day_ID</th>
<th data-quarto-table-cell-role="th">Day_of_Week</th>
<th data-quarto-table-cell-role="th">season_week_rel</th>
<th data-quarto-table-cell-role="th">Is_Holiday</th>
<th data-quarto-table-cell-role="th">Total_Visitors</th>
<th data-quarto-table-cell-role="th">Passholder_Percentage</th>
<th data-quarto-table-cell-role="th">Day_Tickets_Sold</th>
<th data-quarto-table-cell-role="th">Avg_Ticket_Price</th>
<th data-quarto-table-cell-role="th">Gate_Revenue</th>
<th data-quarto-table-cell-role="th">Revenue_Food</th>
<th data-quarto-table-cell-role="th">Revenue_Merch</th>
<th data-quarto-table-cell-role="th">Revenue_Arcade</th>
<th data-quarto-table-cell-role="th">Total_Revenue</th>
<th data-quarto-table-cell-role="th">Total_Labor_Hours</th>
<th data-quarto-table-cell-role="th">International_Visitors</th>
<th data-quarto-table-cell-role="th">High_Temperature</th>
<th data-quarto-table-cell-role="th">Weather_Type</th>
<th data-quarto-table-cell-role="th">Is_Special_Event</th>
<th data-quarto-table-cell-role="th">Per_Capita_Spend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>Monday</td>
<td>1</td>
<td>1</td>
<td>1769</td>
<td>48.65</td>
<td>908</td>
<td>77.42</td>
<td>70297.36</td>
<td>40521.91</td>
<td>15881.290</td>
<td>3195.46</td>
<td>129896.02</td>
<td>238.1</td>
<td>114.0</td>
<td>74.6</td>
<td>Thunderstorms</td>
<td>0</td>
<td>73.43</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>Tuesday</td>
<td>1</td>
<td>0</td>
<td>1717</td>
<td>60.58</td>
<td>677</td>
<td>69.80</td>
<td>47254.60</td>
<td>35298.92</td>
<td>15882.665</td>
<td>2977.63</td>
<td>101812.36</td>
<td>253.4</td>
<td>255.0</td>
<td>74.0</td>
<td>Partly Cloudy</td>
<td>0</td>
<td>59.30</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>Wednesday</td>
<td>1</td>
<td>0</td>
<td>1600</td>
<td>30.84</td>
<td>1107</td>
<td>70.09</td>
<td>77589.63</td>
<td>36495.95</td>
<td>14954.040</td>
<td>2683.58</td>
<td>131723.20</td>
<td>213.3</td>
<td>160.0</td>
<td>76.8</td>
<td>Partly Cloudy</td>
<td>0</td>
<td>82.33</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>Thursday</td>
<td>1</td>
<td>0</td>
<td>1037</td>
<td>19.02</td>
<td>840</td>
<td>72.30</td>
<td>60732.00</td>
<td>22486.65</td>
<td>9517.060</td>
<td>1831.98</td>
<td>94567.69</td>
<td>192.7</td>
<td>83.0</td>
<td>75.4</td>
<td>Showers</td>
<td>0</td>
<td>91.19</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>Friday</td>
<td>1</td>
<td>0</td>
<td>1671</td>
<td>66.18</td>
<td>565</td>
<td>68.11</td>
<td>38482.15</td>
<td>40705.15</td>
<td>15727.620</td>
<td>3115.94</td>
<td>98030.86</td>
<td>235.9</td>
<td>158.0</td>
<td>80.7</td>
<td>Partly Cloudy</td>
<td>0</td>
<td>58.67</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="57d68b18-7bca-4c32-8a4b-422881c7052c" class="cell" data-execution_count="82">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert binary flags (0,1) including: Is_Holiday and Is_Special_Event to categorical</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>day_25[[<span class="st">'Is_Holiday'</span>,<span class="st">'Is_Special_Event'</span>]] <span class="op">=</span> day_25[[<span class="st">'Is_Holiday'</span>,<span class="st">'Is_Special_Event'</span>]].astype(<span class="st">'category'</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert season_week_rel, Day_of_Week and Weather_Type from object to categorical variables</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>day_25[[<span class="st">'Day_of_Week'</span>,<span class="st">'season_week_rel'</span>,<span class="st">'Weather_Type'</span>]] <span class="op">=</span> day_25[[<span class="st">'Day_of_Week'</span>,<span class="st">'season_week_rel'</span>,<span class="st">'Weather_Type'</span>]].astype(<span class="st">'category'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="a144dde0-a438-43d0-a40b-719045b8a0e3" class="cell" data-execution_count="83">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the Day_ID variable</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>day_25 <span class="op">=</span> day_25.drop(columns<span class="op">=</span>[<span class="st">"Day_ID"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In this case, I decided to drop Day_ID because it’s just a sequential label and doesn’t seem to offer meaningful insight for analysis or prediction. Since it might unintentionally influence models by introducing artificial patterns, it felt more appropriate to leave it out of the feature set.</p>
<div id="5d3f1821-e71a-4394-9ec0-99d4a0ad1b79" class="cell" data-execution_count="84">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Double check to see if all the variables are stored as the appropriate data type</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>day_25.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 99 entries, 0 to 98
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype   
---  ------                  --------------  -----   
 0   Day_of_Week             99 non-null     category
 1   season_week_rel         99 non-null     category
 2   Is_Holiday              99 non-null     category
 3   Total_Visitors          99 non-null     int64   
 4   Passholder_Percentage   99 non-null     float64 
 5   Day_Tickets_Sold        99 non-null     int64   
 6   Avg_Ticket_Price        99 non-null     float64 
 7   Gate_Revenue            99 non-null     float64 
 8   Revenue_Food            99 non-null     float64 
 9   Revenue_Merch           99 non-null     float64 
 10  Revenue_Arcade          99 non-null     float64 
 11  Total_Revenue           99 non-null     float64 
 12  Total_Labor_Hours       99 non-null     float64 
 13  International_Visitors  99 non-null     float64 
 14  High_Temperature        99 non-null     float64 
 15  Weather_Type            99 non-null     category
 16  Is_Special_Event        99 non-null     category
 17  Per_Capita_Spend        99 non-null     float64 
dtypes: category(5), float64(11), int64(2)
memory usage: 12.1 KB</code></pre>
</div>
</div>
<ul>
<li><strong>Numeric Variables:</strong> Total_Visitors, Passholder_Percentage, Day_Tickets_Sold, Avg_Ticket_Price, Gate_Revenue, Revenue_Food, Revenue_Merch, Revenue_Arcade, Total_Revenue, Total_Labor_Hours, International_Visitors, High_Temperature, Per_Capita_Spend</li>
<li><strong>Categorical Variables:</strong> Day_ID, Day_of_Week, season_week_rel, Is_Holiday, Weather_Type, Is_Special_Event</li>
</ul>
<p>In my opinion, it’s not a great idea to use categorical inputs in a k-means model because the algorithm calculates distances between data points, and turning categories into numbers can be misleading. Take season_week_rel for example, it uses values from 1 to 15 to represent different weeks, but those numbers don’t really capture how similar or different the weeks are in terms of things like visitor patterns or revenue. The model might end up grouping week 1 and week 2 together just because their numbers are close, even if they behave very differently. Since k-means tries to minimize distance within clusters, it could create groups that look related mathematically but don’t actually make much sense in the real-world context of the data.</p>
<section id="call-the-describe-function-on-your-dataset." class="level4">
<h4 class="anchored" data-anchor-id="call-the-describe-function-on-your-dataset.">Call the describe() function on your dataset.</h4>
<div id="a4513628-c99f-4621-810b-7a9405d97573" class="cell" data-execution_count="85">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>day_25.describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="85">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Total_Visitors</th>
<th data-quarto-table-cell-role="th">Passholder_Percentage</th>
<th data-quarto-table-cell-role="th">Day_Tickets_Sold</th>
<th data-quarto-table-cell-role="th">Avg_Ticket_Price</th>
<th data-quarto-table-cell-role="th">Gate_Revenue</th>
<th data-quarto-table-cell-role="th">Revenue_Food</th>
<th data-quarto-table-cell-role="th">Revenue_Merch</th>
<th data-quarto-table-cell-role="th">Revenue_Arcade</th>
<th data-quarto-table-cell-role="th">Total_Revenue</th>
<th data-quarto-table-cell-role="th">Total_Labor_Hours</th>
<th data-quarto-table-cell-role="th">International_Visitors</th>
<th data-quarto-table-cell-role="th">High_Temperature</th>
<th data-quarto-table-cell-role="th">Per_Capita_Spend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
<td>99.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>1870.707071</td>
<td>41.973232</td>
<td>1098.292929</td>
<td>70.439697</td>
<td>79484.778182</td>
<td>54715.882626</td>
<td>18691.392273</td>
<td>4450.617879</td>
<td>147911.785253</td>
<td>256.535354</td>
<td>178.464646</td>
<td>77.126263</td>
<td>76.930808</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>641.078735</td>
<td>15.581994</td>
<td>466.750518</td>
<td>10.680450</td>
<td>37053.465251</td>
<td>97737.730733</td>
<td>8077.026667</td>
<td>2992.738130</td>
<td>62854.729274</td>
<td>47.232843</td>
<td>85.522800</td>
<td>13.975537</td>
<td>12.582334</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>-50.000000</td>
<td>11.720000</td>
<td>322.000000</td>
<td>-25.000000</td>
<td>22350.020000</td>
<td>22486.650000</td>
<td>9517.060000</td>
<td>1831.980000</td>
<td>63247.570000</td>
<td>192.700000</td>
<td>-10.000000</td>
<td>63.800000</td>
<td>51.630000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>1482.000000</td>
<td>28.895000</td>
<td>771.000000</td>
<td>68.250000</td>
<td>53853.740000</td>
<td>33291.365000</td>
<td>13492.635000</td>
<td>2693.595000</td>
<td>103186.105000</td>
<td>222.400000</td>
<td>117.500000</td>
<td>70.850000</td>
<td>68.575000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>1704.000000</td>
<td>40.900000</td>
<td>995.000000</td>
<td>70.480000</td>
<td>70272.360000</td>
<td>38054.660000</td>
<td>15882.665000</td>
<td>3026.520000</td>
<td>129433.130000</td>
<td>243.500000</td>
<td>158.000000</td>
<td>74.800000</td>
<td>77.500000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>2080.000000</td>
<td>54.590000</td>
<td>1411.000000</td>
<td>73.735000</td>
<td>103147.720000</td>
<td>55612.790000</td>
<td>22567.790000</td>
<td>5419.410000</td>
<td>184173.685000</td>
<td>272.000000</td>
<td>232.500000</td>
<td>81.350000</td>
<td>84.385000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>3938.000000</td>
<td>73.650000</td>
<td>3029.000000</td>
<td>82.280000</td>
<td>242229.130000</td>
<td>999999.990000</td>
<td>51601.440000</td>
<td>15755.610000</td>
<td>423019.370000</td>
<td>435.400000</td>
<td>560.000000</td>
<td>200.000000</td>
<td>110.860000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>When I run the describe() function on this dataset, it provides a concise statistical summary of each numeric column, including the count, mean, standard deviation, and range values. This snapshot helps me quickly understand the distribution and behavior of each variable, which is essential for assessing data quality and preparing for modeling.</p>
<p>In this case, the summary reveals several problematic entries that need attention. For example, <em>Total_Visitors</em>, <em>International_Visitors</em>, and <em>Avg_Ticket_Price</em> contain negative values, which are not realistic in the context of theme park operations. Another noticeable issue in the summary table is that <em>Revenue_Food</em> shows a maximum value of 999,999.99, which exceeds the <em>Total_Revenue</em> maximum of 423,019.37, even though <em>Total_Revenue</em> should represent the combined daily revenue across all categories (gate, food, merchandise, and arcade). Identifying these issues early allows me to flag potential data entry errors or outliers and decide whether to clean, transform, or exclude certain records. This step is crucial for ensuring that the model is built on reliable and interpretable data.</p>
</section>
<section id="missing-values-impossible-values" class="level4">
<h4 class="anchored" data-anchor-id="missing-values-impossible-values">Missing values / Impossible values</h4>
<div id="38092c0f-346f-4a11-a0c9-ac02adde3bb1" class="cell" data-execution_count="86">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>day_25.isnull().<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="86">
<pre><code>Day_of_Week               0
season_week_rel           0
Is_Holiday                0
Total_Visitors            0
Passholder_Percentage     0
Day_Tickets_Sold          0
Avg_Ticket_Price          0
Gate_Revenue              0
Revenue_Food              0
Revenue_Merch             0
Revenue_Arcade            0
Total_Revenue             0
Total_Labor_Hours         0
International_Visitors    0
High_Temperature          0
Weather_Type              0
Is_Special_Event          0
Per_Capita_Spend          0
dtype: int64</code></pre>
</div>
</div>
<p>After running the code and checking the results for missing values, the output indicates that all columns contain zero missing values, suggesting that the dataset is complete and no data cleaning through imputation or row removal is necessary.</p>
<div id="96c50b6d-1bce-466e-978a-a1a7ea8dee45" class="cell" data-execution_count="87">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>day_25.select_dtypes(include<span class="op">=</span><span class="st">"number"</span>).lt(<span class="dv">0</span>).<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="87">
<pre><code>Total_Visitors            1
Passholder_Percentage     0
Day_Tickets_Sold          0
Avg_Ticket_Price          1
Gate_Revenue              0
Revenue_Food              0
Revenue_Merch             0
Revenue_Arcade            0
Total_Revenue             0
Total_Labor_Hours         0
International_Visitors    1
High_Temperature          0
Per_Capita_Spend          0
dtype: int64</code></pre>
</div>
</div>
<div id="01a570fd-7890-4e6b-b2b4-e93fcad01440" class="cell" data-execution_count="88">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look for rows with negative values in Total_Visitors, Avg_Ticket_Price and International_Visitors </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>day_25[(day_25[<span class="st">"Total_Visitors"</span>] <span class="op">&lt;</span> <span class="dv">0</span>) <span class="op">|</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>       (day_25[<span class="st">"Avg_Ticket_Price"</span>] <span class="op">&lt;</span> <span class="dv">0</span>) <span class="op">|</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>       (day_25[<span class="st">"International_Visitors"</span>] <span class="op">&lt;</span> <span class="dv">0</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="88">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Day_of_Week</th>
<th data-quarto-table-cell-role="th">season_week_rel</th>
<th data-quarto-table-cell-role="th">Is_Holiday</th>
<th data-quarto-table-cell-role="th">Total_Visitors</th>
<th data-quarto-table-cell-role="th">Passholder_Percentage</th>
<th data-quarto-table-cell-role="th">Day_Tickets_Sold</th>
<th data-quarto-table-cell-role="th">Avg_Ticket_Price</th>
<th data-quarto-table-cell-role="th">Gate_Revenue</th>
<th data-quarto-table-cell-role="th">Revenue_Food</th>
<th data-quarto-table-cell-role="th">Revenue_Merch</th>
<th data-quarto-table-cell-role="th">Revenue_Arcade</th>
<th data-quarto-table-cell-role="th">Total_Revenue</th>
<th data-quarto-table-cell-role="th">Total_Labor_Hours</th>
<th data-quarto-table-cell-role="th">International_Visitors</th>
<th data-quarto-table-cell-role="th">High_Temperature</th>
<th data-quarto-table-cell-role="th">Weather_Type</th>
<th data-quarto-table-cell-role="th">Is_Special_Event</th>
<th data-quarto-table-cell-role="th">Per_Capita_Spend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Thursday</td>
<td>2</td>
<td>0</td>
<td>-50</td>
<td>72.26</td>
<td>444</td>
<td>69.49</td>
<td>30853.56</td>
<td>40019.25</td>
<td>15179.56</td>
<td>2722.04</td>
<td>88774.41</td>
<td>228.6</td>
<td>75.0</td>
<td>82.4</td>
<td>Partly Cloudy</td>
<td>0</td>
<td>55.52</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20</th>
<td>Sunday</td>
<td>3</td>
<td>0</td>
<td>2691</td>
<td>27.24</td>
<td>1958</td>
<td>-25.00</td>
<td>146771.68</td>
<td>67432.83</td>
<td>26147.56</td>
<td>7571.99</td>
<td>247924.06</td>
<td>305.3</td>
<td>178.0</td>
<td>79.5</td>
<td>Cloudy</td>
<td>0</td>
<td>92.13</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">50</th>
<td>Tuesday</td>
<td>8</td>
<td>0</td>
<td>1204</td>
<td>72.60</td>
<td>330</td>
<td>68.39</td>
<td>22568.70</td>
<td>27999.37</td>
<td>11246.96</td>
<td>2202.88</td>
<td>64017.91</td>
<td>205.4</td>
<td>-10.0</td>
<td>78.0</td>
<td>Rain</td>
<td>0</td>
<td>53.17</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cefcda4e-b0cf-41bd-9855-8ab6d3c84982" class="cell" data-execution_count="89">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find rows with suspiciously high food revenue</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>day_25[day_25[<span class="st">"Revenue_Food"</span>] <span class="op">&gt;</span> day_25[<span class="st">"Total_Revenue"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="89">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Day_of_Week</th>
<th data-quarto-table-cell-role="th">season_week_rel</th>
<th data-quarto-table-cell-role="th">Is_Holiday</th>
<th data-quarto-table-cell-role="th">Total_Visitors</th>
<th data-quarto-table-cell-role="th">Passholder_Percentage</th>
<th data-quarto-table-cell-role="th">Day_Tickets_Sold</th>
<th data-quarto-table-cell-role="th">Avg_Ticket_Price</th>
<th data-quarto-table-cell-role="th">Gate_Revenue</th>
<th data-quarto-table-cell-role="th">Revenue_Food</th>
<th data-quarto-table-cell-role="th">Revenue_Merch</th>
<th data-quarto-table-cell-role="th">Revenue_Arcade</th>
<th data-quarto-table-cell-role="th">Total_Revenue</th>
<th data-quarto-table-cell-role="th">Total_Labor_Hours</th>
<th data-quarto-table-cell-role="th">International_Visitors</th>
<th data-quarto-table-cell-role="th">High_Temperature</th>
<th data-quarto-table-cell-role="th">Weather_Type</th>
<th data-quarto-table-cell-role="th">Is_Special_Event</th>
<th data-quarto-table-cell-role="th">Per_Capita_Spend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">30</th>
<td>Wednesday</td>
<td>5</td>
<td>0</td>
<td>1772</td>
<td>18.77</td>
<td>1439</td>
<td>69.82</td>
<td>100470.98</td>
<td>999999.99</td>
<td>16262.36</td>
<td>2974.24</td>
<td>165467.64</td>
<td>238.3</td>
<td>137.0</td>
<td>86.4</td>
<td>Cloudy</td>
<td>0</td>
<td>93.38</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="bd702d81-a304-471f-b49e-d2218ad56e52" class="cell" data-execution_count="90">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find rows with suspiciosly high temperature </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>day_25[day_25[<span class="st">"High_Temperature"</span>] <span class="op">&gt;</span> <span class="dv">120</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="90">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Day_of_Week</th>
<th data-quarto-table-cell-role="th">season_week_rel</th>
<th data-quarto-table-cell-role="th">Is_Holiday</th>
<th data-quarto-table-cell-role="th">Total_Visitors</th>
<th data-quarto-table-cell-role="th">Passholder_Percentage</th>
<th data-quarto-table-cell-role="th">Day_Tickets_Sold</th>
<th data-quarto-table-cell-role="th">Avg_Ticket_Price</th>
<th data-quarto-table-cell-role="th">Gate_Revenue</th>
<th data-quarto-table-cell-role="th">Revenue_Food</th>
<th data-quarto-table-cell-role="th">Revenue_Merch</th>
<th data-quarto-table-cell-role="th">Revenue_Arcade</th>
<th data-quarto-table-cell-role="th">Total_Revenue</th>
<th data-quarto-table-cell-role="th">Total_Labor_Hours</th>
<th data-quarto-table-cell-role="th">International_Visitors</th>
<th data-quarto-table-cell-role="th">High_Temperature</th>
<th data-quarto-table-cell-role="th">Weather_Type</th>
<th data-quarto-table-cell-role="th">Is_Special_Event</th>
<th data-quarto-table-cell-role="th">Per_Capita_Spend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">40</th>
<td>Saturday</td>
<td>6</td>
<td>0</td>
<td>1933</td>
<td>25.14</td>
<td>1447</td>
<td>74.99</td>
<td>108510.53</td>
<td>54861.67</td>
<td>19528.12</td>
<td>5038.63</td>
<td>187938.95</td>
<td>251.4</td>
<td>194.0</td>
<td>200.0</td>
<td>Rain</td>
<td>0</td>
<td>97.23</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To identify impossible values, I focused on numeric variables and used the command day_25.select_dtypes(include=“number”).lt(0).sum(). This function isolates numeric columns and checks for any values less than zero, providing a quick count of negative entries per column. This approach is useful because variables like visitor counts, ticket sales, and revenue figures cannot logically be negative in a theme park setting. At the same time, <em>Passholder_Percentage</em> falls within a reasonable 0–100% range, so those values appear consistent.</p>
<p>The results showed three impossible values in <em>Total_Visitors, International_Visitors, and Avg_Ticket_Price</em>. These values are considered impossible because visitor counts cannot be negative - they must be zero or greater. Similarly, ticket prices are typically non-negative, unless there’s a rare case involving refunds or discounts. In this context, negative values likely indicate data entry errors or corrupted records.</p>
<p>The summary statistics also showed that <em>Revenue_Food</em> has a maximum value of 999,999.99, whereas Total_Revenue only has a maximum of 423,019.37. Because Total_Revenue should include all revenue categories, this should be corrected or reviewed before any further analysis.</p>
<p>Another entry that appears suspicious is <em>High_Temperature</em>, which shows a maximum value of 200°F. While temperature ranges can vary by region, typical readings in the United States generally fall between 0°F and a little over 100°F. Even Boston’s recent heatwave only reached a record high of 102°F, so a value of 200°F is unrealistic. To verify, I filtered the <em>High_Temperature</em> variable for values greater than 120°F and found only one record, suggesting this is likely a data entry or recording error.</p>
</section>
<section id="if-so-handle-them-in-any-way-that-you-see-fit." class="level4">
<h4 class="anchored" data-anchor-id="if-so-handle-them-in-any-way-that-you-see-fit.">If so, handle them in any way that you see fit.</h4>
<div id="92b526c6-2b3b-46fc-97c5-df3250db639a" class="cell" data-execution_count="91">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows where Food_Revenue exceeds Total_Revenue</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>day_25 <span class="op">=</span> day_25[day_25[<span class="st">"Revenue_Food"</span>] <span class="op">&lt;=</span> day_25[<span class="st">"Total_Revenue"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In this case, the simplest and most reasonable solution is to remove the entire row, since even if I replaced <em>Revenue_Food</em> with a typical value (like the median), <em>Total_Revenue</em> would still end up smaller than the sum of its parts, which doesn’t make sense for this dataset.</p>
<div id="3e43fa5d-5c8d-4d65-bb31-56f8afca23fa" class="cell" data-execution_count="92">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows where  High_Temperature is abnormally high</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>day_25 <span class="op">=</span> day_25[day_25[<span class="st">"High_Temperature"</span>] <span class="op">&lt;=</span> <span class="dv">120</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I decided to remove the row with the unusually high temperature value instead of imputing it with the median, since it appeared to be an outlier that could distort the results. By removing it, I ensure the dataset remains accurate and free from unrealistic values.</p>
<div id="491b9140-c226-438e-b51f-81f4d428df79" class="cell" data-execution_count="93">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter so that all variables is non-negative</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>day25 <span class="op">=</span> day_25[</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    (day_25[<span class="st">"Total_Visitors"</span>] <span class="op">&gt;=</span> <span class="dv">0</span>) <span class="op">&amp;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    (day_25[<span class="st">"Avg_Ticket_Price"</span>] <span class="op">&gt;=</span> <span class="dv">0</span>) <span class="op">&amp;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    (day_25[<span class="st">"International_Visitors"</span>] <span class="op">&gt;=</span> <span class="dv">0</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>day25.select_dtypes(include<span class="op">=</span><span class="st">"number"</span>).lt(<span class="dv">0</span>).<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="93">
<pre><code>Total_Visitors            0
Passholder_Percentage     0
Day_Tickets_Sold          0
Avg_Ticket_Price          0
Gate_Revenue              0
Revenue_Food              0
Revenue_Merch             0
Revenue_Arcade            0
Total_Revenue             0
Total_Labor_Hours         0
International_Visitors    0
High_Temperature          0
Per_Capita_Spend          0
dtype: int64</code></pre>
</div>
</div>
<div id="f7e4e303-8b4a-4228-bf4f-af24a5f4f105" class="cell" data-scrolled="true" data-execution_count="94">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now, day25 dataframe has 94 entries for each variable after dropping the 5 impossible rows.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>day25.count()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="94">
<pre><code>Day_of_Week               94
season_week_rel           94
Is_Holiday                94
Total_Visitors            94
Passholder_Percentage     94
Day_Tickets_Sold          94
Avg_Ticket_Price          94
Gate_Revenue              94
Revenue_Food              94
Revenue_Merch             94
Revenue_Arcade            94
Total_Revenue             94
Total_Labor_Hours         94
International_Visitors    94
High_Temperature          94
Weather_Type              94
Is_Special_Event          94
Per_Capita_Spend          94
dtype: int64</code></pre>
</div>
</div>
<p>I chose to drop the rows with impossible values rather than replace them with the median or mode because the errors are rare and clearly invalid. According to data_25.info() results above, I know that there are 99 entries for each variables. With only 5 affected entries out of 99, removing them avoids introducing assumptions that could distort relationships between variables. Replacing with typical values like the median might mask underlying issues or flatten meaningful variation, especially when the context behind the error is unknown. Dropping ensures the dataset remains clean and reasonable.</p>
</section>
<section id="variable-selection.-select-any-5-variables-from-the-potential-set-of-inputs-in-order-to-build-your-k-means-clustering-model." class="level4">
<h4 class="anchored" data-anchor-id="variable-selection.-select-any-5-variables-from-the-potential-set-of-inputs-in-order-to-build-your-k-means-clustering-model.">Variable selection. Select any 5 variables from the potential set of inputs in order to build your k-means clustering model.</h4>
<div id="16270567-239a-40bc-b71c-40e21eadbe79" class="cell" data-execution_count="95">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>var_selected <span class="op">=</span> day25[[<span class="st">"Total_Visitors"</span>,<span class="st">"Avg_Ticket_Price"</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"High_Temperature"</span>,<span class="st">"Passholder_Percentage"</span>,<span class="st">"Per_Capita_Spend"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To build a meaningful k-means clustering model, I selected the following five variables from the dataset: <em>Total_Visitors, Avg_Ticket_Price, High_Temperature, Passholder_Percentage, and Per_Capita_Spend</em>. These five variables were chosen to capture key aspects of daily park dynamics. <em>Total_Visitors</em> reflects overall attendance, giving a sense of how busy the park is. <em>Avg_Ticket_Price</em> ties into pricing strategy and its potential influence on visitor volume. <em>High_Temperature</em> displays a weather factor that can affect both attendance and spending. <em>Passholder_Percentage</em> helps distinguish between loyal visitors and one-time guests, which may impact behavior and spending habits. <em>Per_Capita_Spend</em> offers a normalized view of how much each visitor contributes financially, combining attendance and revenue into a single meaningful metric.</p>
</section>
<section id="data-scaling" class="level4">
<h4 class="anchored" data-anchor-id="data-scaling">Data Scaling</h4>
</section>
<section id="do-your-variables-need-to-be-standardized-why-or-why-not" class="level4">
<h4 class="anchored" data-anchor-id="do-your-variables-need-to-be-standardized-why-or-why-not">Do your variables need to be standardized? Why or why not?</h4>
<p>Yes, I do think my variables should be standardized before applying k-means clustering. This is because they are measured on very different scales. For instance, <em>Avg_Ticket_Price</em> is no more than about $83, while Total_Visitors can reach nearly 4,000, which is a much larger numerical range. Similarly, <em>Passholder_Percentage</em> is expressed as a proportion (0–100%), and <em>High_Temperature</em> and <em>Per_Capita_Spend</em> also exist on their own distinct scales. Since k-means uses Euclidean distance to group observations, variables with larger numeric ranges would otherwise dominate the clustering process. Standardizing the data ensures that each variable contributes equally to distance calculations, leading to more balanced and meaningful clusters.</p>
</section>
<section id="if-your-data-requires-standardization-use-python-to-convert-your-values-into-z-scores-and-store-the-normalized-data-in-a-new-dataframe.-if-not-proceed-to-the-next-step-without-changing-the-variables." class="level4">
<h4 class="anchored" data-anchor-id="if-your-data-requires-standardization-use-python-to-convert-your-values-into-z-scores-and-store-the-normalized-data-in-a-new-dataframe.-if-not-proceed-to-the-next-step-without-changing-the-variables.">If your data requires standardization, use Python to convert your values into z-scores, and store the normalized data in a new dataframe. If not, proceed to the next step without changing the variables.</h4>
<div id="97673bec-65fb-48ed-a448-1512eb25c92c" class="cell" data-execution_count="96">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import scaler function to standardize dataframe</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>var_scaled <span class="op">=</span> scaler.fit_transform(var_selected)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new dataframe with standardized values</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>var_scaled_df <span class="op">=</span> pd.DataFrame(var_scaled, columns <span class="op">=</span> var_selected.columns)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(var_scaled_df.head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Total_Visitors  Avg_Ticket_Price  High_Temperature  Passholder_Percentage  \
0       -0.196940          1.312127         -0.163867               0.452158   
1       -0.281650         -0.361277         -0.259344               1.252239   
2       -0.472247         -0.297591          0.186213              -0.742262   
3       -1.389393          0.187740         -0.036565              -1.534966   
4       -0.356585         -0.732412          0.806810               1.627801   

   Per_Capita_Spend  
0         -0.285287  
1         -1.460976  
2          0.455238  
3          1.192436  
4         -1.513395  </code></pre>
</div>
</div>
</section>
<section id="elbow-chart" class="level4">
<h4 class="anchored" data-anchor-id="elbow-chart">Elbow Chart</h4>
<div id="d67e0f21-3576-4f91-b356-08d3dd1c0f95" class="cell" data-execution_count="97">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define X with 5 selected columns from the standardized data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> var_scaled_df[[<span class="st">"Total_Visitors"</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Avg_Ticket_Price"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"High_Temperature"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Passholder_Percentage"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Per_Capita_Spend"</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                  ]]</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the elbow chart</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>sse <span class="op">=</span> []</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>cluster_range <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">15</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> cluster_range:</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    kmeans <span class="op">=</span> KMeans(n_clusters<span class="op">=</span>k, random_state<span class="op">=</span><span class="dv">616</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    kmeans.fit(X)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    sse.append(kmeans.inertia_)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the Elbow chart</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>plt.plot(cluster_range, sse, marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Clusters"</span>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"SSE (Sum of Squared Errors)"</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Elbow Chart for K-means Clustering"</span>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>plt.xticks(cluster_range)</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="market_segment_conjoint_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-many-clusters-will-you-use-for-your-k-means-model" class="level4">
<h4 class="anchored" data-anchor-id="how-many-clusters-will-you-use-for-your-k-means-model">How many clusters will you use for your k-means model?</h4>
<p>The elbow chart above shows the SSE decreasing sharply from around 480 to approximately 175 as the number of clusters increases. The most significant drop occurs between 1 and 4 clusters, after which the curve begins to flatten, suggesting diminishing returns from adding more clusters. Based on this pattern, I selected k = 4 for the k-means model, as it captures most of the variance in the data while maintaining a manageable number of segments.</p>
<p>A smaller number of clusters (e.g., 2 or 3) would likely combine distinct park-day types, such as slower weekdays and peak weekends - into the same group, masking meaningful operational differences. By using four clusters, the park can better understand how key factors like visitor volume, pricing, weather, and spending behavior interact across different day types.</p>
</section>
<section id="build-a-k-means-model-with-your-desired-number-of-clusters." class="level4">
<h4 class="anchored" data-anchor-id="build-a-k-means-model-with-your-desired-number-of-clusters.">Build a k-means model with your desired number of clusters.</h4>
<div id="1548702f-c1e3-4789-8539-787bf696f1de" class="cell" data-execution_count="98">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build and fit the K-Means model on the standardized DataFrame 'X'</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>kmeans_model <span class="op">=</span> KMeans(n_clusters <span class="op">=</span> <span class="dv">4</span>, random_state <span class="op">=</span> <span class="dv">616</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>kmeans_model.fit(X)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Add cluster labels to the original standardized df</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>var_scaled_df[<span class="st">'Cluster'</span>] <span class="op">=</span> kmeans_model.labels_</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"K-Means Cluster Centers (for 4 clusters):"</span>)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(var_scaled_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>K-Means Cluster Centers (for 4 clusters):
    Total_Visitors  Avg_Ticket_Price  High_Temperature  Passholder_Percentage  \
0        -0.196940          1.312127         -0.163867               0.452158   
1        -0.281650         -0.361277         -0.259344               1.252239   
2        -0.472247         -0.297591          0.186213              -0.742262   
3        -1.389393          0.187740         -0.036565              -1.534966   
4        -0.356585         -0.732412          0.806810               1.627801   
..             ...               ...               ...                    ...   
89       -0.742667         -0.567707         -0.084304              -0.679222   
90       -0.242553         -0.211944         -1.325497              -0.760370   
91        1.531466          1.031030         -0.609424              -0.212452   
92       -0.009601         -0.225120         -0.800377               0.871312   
93        0.837497          0.752130         -0.338907              -0.750310   

    Per_Capita_Spend  Cluster  
0          -0.285287        0  
1          -1.460976        0  
2           0.455238        3  
3           1.192436        3  
4          -1.513395        1  
..               ...      ...  
89          0.366209        3  
90          0.213943        3  
91          0.434437        2  
92         -0.678848        0  
93          0.615824        3  

[94 rows x 6 columns]</code></pre>
</div>
</div>
<p>I built the k-means model using a data frame containing only the 5 selected variables. By setting random_state = 616, I ensured that the clustering results remain consistent across runs. I selected 3 clusters to achieve a more detailed and meaningful segmentation of the park.</p>
</section>
<section id="generate-centroid-values" class="level4">
<h4 class="anchored" data-anchor-id="generate-centroid-values">Generate Centroid Values</h4>
<div id="d875049e-46e5-4c64-b8e5-548602efa563" class="cell" data-execution_count="99">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate centroid values for each cluster</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>centroids <span class="op">=</span> var_scaled_df.groupby(<span class="st">'Cluster'</span>).mean()</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the centroids</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(centroids)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Total_Visitors  Avg_Ticket_Price  High_Temperature  \
Cluster                                                       
0             -0.592234         -0.358172         -0.670880   
1             -0.295578         -0.381371          1.168029   
2              1.977070          1.522274          0.319635   
3             -0.081737         -0.055474         -0.251885   

         Passholder_Percentage  Per_Capita_Spend  
Cluster                                           
0                     0.643200         -0.830625  
1                     0.596481         -0.552168  
2                     0.303739          0.530955  
3                    -1.079094          0.882159  </code></pre>
</div>
</div>
<div id="75cb45cf-a26f-43cb-b25d-d68103c69d92" class="cell" data-execution_count="100">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cluster_counts <span class="op">=</span> var_scaled_df[<span class="st">'Cluster'</span>].value_counts().sort_index()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Cluster Counts:"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cluster_counts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Cluster Counts:
Cluster
0    29
1    20
2    13
3    32
Name: count, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="build-four-simple-visualizations-to-help-management-better-understand-your-clusters" class="level4">
<h4 class="anchored" data-anchor-id="build-four-simple-visualizations-to-help-management-better-understand-your-clusters">Build four simple visualizations to help management better understand your clusters</h4>
</section>
<section id="visualization-1-histogram-of-total-visitors-by-cluster" class="level4">
<h4 class="anchored" data-anchor-id="visualization-1-histogram-of-total-visitors-by-cluster">Visualization 1: Histogram of Total Visitors by Cluster</h4>
<div id="e2b29716-545e-4671-abbe-0283a27b2729" class="cell" data-scrolled="true" data-execution_count="101">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>var_scaled_df, x<span class="op">=</span><span class="st">"Total_Visitors"</span>, hue<span class="op">=</span><span class="st">"Cluster"</span>, multiple<span class="op">=</span><span class="st">"stack"</span>, palette<span class="op">=</span><span class="st">"Set2"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Total Visitors by Cluster"</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Total Visitors (Standardized)"</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="market_segment_conjoint_files/figure-html/cell-25-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This histogram shows the distribution of Total Visitors(standardized) across the four clusters groupped by the model, with the x-axis representing Total Visitors to Lobster Land and the y-axis showing their frequency. Cluster 0 (green) is concentrated around lower standardized visitor counts, suggesting it represents quieter, low-traffic days. Cluster 1 (orange) sits in the middle, reflecting moderate visitor days, not too busy nor too quiet. Cluster 2 (blue) dominates the higher end of the scale, capturing peak attendance periods, while Cluster 3 (pink) spans wider range, suggesting it includes a more diverse mix of visitors who vary from occasional guests to highly engaged ones.</p>
<p>Although this is a simple chart, it’s crucial for Lobster Land, as it clearly shows how each cluster reacts differently in terms of attendance and helps the team plan targeted promotions and engagement strategies tailored to each group’s behavior.</p>
</section>
<section id="visualization-2-barplot-average-ticket-price-per-cluster" class="level4">
<h4 class="anchored" data-anchor-id="visualization-2-barplot-average-ticket-price-per-cluster">Visualization 2: Barplot Average Ticket Price per Cluster</h4>
<div id="b81e6f04-3e0f-4acb-bf98-bc70ee72701a" class="cell" data-execution_count="102">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>sns.barplot(data<span class="op">=</span>var_scaled_df, x<span class="op">=</span><span class="st">"Cluster"</span>, y<span class="op">=</span><span class="st">"Avg_Ticket_Price"</span>, hue<span class="op">=</span><span class="st">"Cluster"</span>, palette<span class="op">=</span><span class="st">"Set2"</span>, dodge<span class="op">=</span><span class="va">False</span>, legend<span class="op">=</span><span class="va">False</span>, edgecolor<span class="op">=</span><span class="st">"black"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Average Ticket Price per Cluster"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Cluster"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Average Ticket Price (Standardized)"</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="market_segment_conjoint_files/figure-html/cell-26-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This bar chart illustrates the mean standardized average ticket price across the four clusters identified by the model. Cluster 2 (blue) shows the highest average ticket price, representing premium or high-demand days. Clusters 0 (green) and 1 (orange) display below-average ticket prices, with Cluster 1 slightly lower than Cluster 0, indicating more budget-friendly or passholder-heavy days. Cluster 3 (pink) remains close to the standardized mean, reflecting more typical pricing conditions across Lobster Land’s visitor segments. This chart helps Lobster Land better understand how ticket prices vary across different visitor groups, allowing the team to align pricing strategies and promotions with each segment’s spending behavior.</p>
</section>
<section id="visualization-3-scatterplot-of-passholder-percentage-vs-per-capita-spend-colored-by-cluster" class="level4">
<h4 class="anchored" data-anchor-id="visualization-3-scatterplot-of-passholder-percentage-vs-per-capita-spend-colored-by-cluster">Visualization 3: Scatterplot of Passholder Percentage vs Per Capita Spend colored by Cluster</h4>
<div id="286283be-7317-457f-b0f1-40139730b337" class="cell" data-execution_count="103">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>var_scaled_df, x<span class="op">=</span><span class="st">"Passholder_Percentage"</span>, y<span class="op">=</span><span class="st">"Per_Capita_Spend"</span>, hue<span class="op">=</span><span class="st">"Cluster"</span>, palette<span class="op">=</span><span class="st">"Set2"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Passholder Percentage vs Per Capita Spend by Cluster"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Passholder Percentage"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Per Capita Spend"</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="market_segment_conjoint_files/figure-html/cell-27-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This scatter plot shows how Passholder Percentage relates to Per Capita Spend across the four clusters identified by the model. I noticed a clear pattern where clusters with a higher share of passholders tend to have lower spending per person, while those with fewer passholders show higher spending levels. Cluster 0 (green) has a wide range of passholder percentages but generally lower spending, whereas Cluster 3 (pink) stands out with a smaller share of passholders and higher spending, likely representing one-time or premium visitors. Whereas Cluster 2 (blue) shows a distinct profile, with moderate passholder percentages and positive per capita spending, reflecting a balanced mix of loyal and casual visitors at Lobster Land. From this chart, we can see how different visitor types behave at Lobster Land, helping identify ways to balance loyalty programs with opportunities to attract higher-value guests.</p>
</section>
<section id="visualization-4-boxplot-high_temperature-per-cluster" class="level4">
<h4 class="anchored" data-anchor-id="visualization-4-boxplot-high_temperature-per-cluster">Visualization 4: Boxplot High_Temperature per Cluster</h4>
<div id="d93002a1-27c4-49b6-b523-dfc8c444b3e0" class="cell" data-execution_count="104">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>var_scaled_df, x<span class="op">=</span><span class="st">"Cluster"</span>, y<span class="op">=</span><span class="st">"High_Temperature"</span>, hue<span class="op">=</span><span class="st">"Cluster"</span>, palette<span class="op">=</span><span class="st">"Set2"</span>, dodge<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"High Temperature by Cluster"</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Cluster"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"High Temperature (Standardized)"</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="market_segment_conjoint_files/figure-html/cell-28-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This boxplot shows how standardized high temperatures vary across the four clusters identified by the model. Cluster 1 (orange) has the highest median temperature, representing hotter days, while Clusters 0 (green) and 3 (pink) are generally cooler. Cluster 2 (blue) shows the widest temperature range, including both hot and cool days, which may reflect mixed or transitional seasonal conditions at Lobster Land.</p>
</section>
<section id="cluster-descriptions" class="level4">
<h4 class="anchored" data-anchor-id="cluster-descriptions">Cluster Descriptions</h4>
</section>
<section id="cluster-0-chill-sparse" class="level4">
<h4 class="anchored" data-anchor-id="cluster-0-chill-sparse">Cluster 0: “Chill &amp; Sparse”</h4>
<p>These are the cool, calm days with lower visitor counts, below-average ticket prices, and a higher share of passholders. Spending per person is lighter, creating an easygoing park atmosphere that appeals to loyal guests and locals who enjoy a quieter visit. - <strong>Targeting:</strong> LobsterLand can focus on community connections and rewarding frequent visitors on these days. Promotions highlighting relaxed park experiences, quiet attractions, or weekday benefits can draw local families and passholders seeking a slower, more comfortable visit.</p>
</section>
<section id="cluster-1-scorch-stroll" class="level4">
<h4 class="anchored" data-anchor-id="cluster-1-scorch-stroll">Cluster 1: “Scorch &amp; Stroll”</h4>
<p>This cluster displays the warmest temperatures, moderate attendance, and lower ticket prices. Spending per capita is modest, and many visitors hold passes, creating a steady but easygoing flow of activity across the park. - <strong>Targeting:</strong> The marketing team can emphasize refreshment and comfort through shaded seating, cool treat bundles or special water rides. Bright and refreshing summer campaigns that highlight leisurely fun and family-friendly attractions can reach guests looking for simple, enjoyable park days.</p>
</section>
<section id="cluster-2-gold-rush-days" class="level4">
<h4 class="anchored" data-anchor-id="cluster-2-gold-rush-days">Cluster 2: “Gold Rush Days”</h4>
<p>Cluster 2 represents the park’s busiest, most profitable days with high visitor counts, the highest standardized ticket prices, and strong per capita spending. With a balanced mix of loyal and casual visitors, these are the moments when the park operates at full capacity and captures its greatest market potential. - <strong>Targeting:</strong> These days can spotlight premium experiences such as fast passes, dining packages, and exclusive access areas. Promotions on travel platforms and event partnerships can reach visitors planning full-day trips or group outings, aligning offerings with elevated park energy and spending activity.</p>
</section>
<section id="cluster-3-balanced-buzz" class="level4">
<h4 class="anchored" data-anchor-id="cluster-3-balanced-buzz">Cluster 3: “Balanced Buzz”</h4>
<p>This cluster shows moderate temperatures, mixed visitor counts, and steady spending levels. Ticket prices remain close to the average, and the lower passholder percentage suggests a healthy mix of new and returning guests. - <strong>Targeting:</strong> With a blend of loyal customers and newcomers, LobsterLand can use this opportunity to run limited-time offers, themed events, or new experiences can help identify emerging interests.</p>
</section>
<section id="how-can-lobster-land-use-this-model" class="level4">
<h4 class="anchored" data-anchor-id="how-can-lobster-land-use-this-model">How can Lobster Land use this model?</h4>
<p>Lobster Land can use this day-type clustering model as a practical tool to help the team make better decisions about staffing, pricing, and creating great experiences for guests. By figuring out which cluster an upcoming day fits into, like a busy “Gold Rush Day” or a quieter “Chill &amp; Sparse” day, the team can get ahead of operations instead of just reacting. On high-traffic days, the park can bring in extra staff, stay open later, and offer special upgrades that guests will actually want. On slower days, there’s room to focus on rewarding regulars, running leaner operations, or taking care of behind-the-scenes maintenance that’s hard to do when the park is packed.</p>
<p>The marketing team can also use these insights to shape promotions that actually fit the day. Take “Scorch &amp; Stroll” days, for instance. These hot, leisurely days might be perfect for promoting cold drink bundles or access to shaded seating areas. “Balannced Buzz” days, with their unexpected energy, could be a testing ground for new attractions or digital campaigns to see what resonates. As Lobster Land builds out this approach, weaving in weather forecasts and calendar events could help predict cluster assignments days or even weeks ahead. That shifts the park from reactive scrambling to a proactive, rhythm-based planning style that aligns operations with real guest patterns and business priorities.</p>
<p>If the team could predict which cluster a day might fall into, it would make planning feel a lot more purposeful and efficient. For instance, if an upcoming weekend looks like a “Gold Rush Day,” the park could bring in extra staff, stock up on food and drinks, and roll out seasonal specials like fall-inspired treats or Halloween-themed beverages to attract both new visitors and returning fans. On the other hand, if a slower Tuesday seems to fall into the “Chill &amp; Sparse” cluster, Lobster Land could use the opportunity to run local promotions, offer discounted afternoon passes, or host a cozy themed dining night for family and friends. This kind of planning helps the park stay balanced—keeping operations efficient, guests happy, and business decisions aligned with real demand.</p>
</section>
</section>
<section id="part-ii-conjoint-analysis-with-a-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-conjoint-analysis-with-a-linear-model">Part II: Conjoint Analysis with a Linear Model</h2>
<div id="759336ef-19f5-40f8-afce-bec08ff8a747" class="cell" data-execution_count="105">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import night_show.csv files into python for use</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>night_show <span class="op">=</span> pd.read_csv(<span class="st">"/Users/nhattran/Downloads/MSBA/METAD654 - Marketing Analytics/assignment 2/night_show.csv"</span>,keep_default_na<span class="op">=</span><span class="va">False</span>, na_values<span class="op">=</span>[])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="9e96f2ce-46b5-486a-a143-3ef65ac31ce0" class="cell" data-execution_count="106">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>night_show.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 73728 entries, 0 to 73727
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   bundleID          73728 non-null  int64  
 1   headliner         73728 non-null  object 
 2   music_atmosphere  73728 non-null  object 
 3   show_length       73728 non-null  int64  
 4   peak_dB_Level     73728 non-null  int64  
 5   crowding_index    73728 non-null  int64  
 6   viewing_zone      73728 non-null  object 
 7   dining_bundle     73728 non-null  object 
 8   re_entry          73728 non-null  object 
 9   live_host         73728 non-null  object 
 10  charity_tie_in    73728 non-null  object 
 11  ratings           73728 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 6.8+ MB</code></pre>
</div>
</div>
<div id="fdf8fb76-e03e-4ac0-af7b-6b7463f587cf" class="cell" data-execution_count="107">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>night_show.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="107">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">bundleID</th>
<th data-quarto-table-cell-role="th">headliner</th>
<th data-quarto-table-cell-role="th">music_atmosphere</th>
<th data-quarto-table-cell-role="th">show_length</th>
<th data-quarto-table-cell-role="th">peak_dB_Level</th>
<th data-quarto-table-cell-role="th">crowding_index</th>
<th data-quarto-table-cell-role="th">viewing_zone</th>
<th data-quarto-table-cell-role="th">dining_bundle</th>
<th data-quarto-table-cell-role="th">re_entry</th>
<th data-quarto-table-cell-role="th">live_host</th>
<th data-quarto-table-cell-role="th">charity_tie_in</th>
<th data-quarto-table-cell-role="th">ratings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>Fireworks</td>
<td>Pop Soundtrack</td>
<td>30</td>
<td>65</td>
<td>40</td>
<td>front plaza</td>
<td>None</td>
<td>None</td>
<td>Yes</td>
<td>Yes</td>
<td>4.249</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>Fireworks</td>
<td>Pop Soundtrack</td>
<td>30</td>
<td>65</td>
<td>40</td>
<td>front plaza</td>
<td>None</td>
<td>None</td>
<td>Yes</td>
<td>No/Doesn't Matter</td>
<td>4.689</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>Fireworks</td>
<td>Pop Soundtrack</td>
<td>30</td>
<td>65</td>
<td>40</td>
<td>front plaza</td>
<td>None</td>
<td>None</td>
<td>No/Doesn't Matter</td>
<td>Yes</td>
<td>7.999</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>Fireworks</td>
<td>Pop Soundtrack</td>
<td>30</td>
<td>65</td>
<td>40</td>
<td>front plaza</td>
<td>None</td>
<td>None</td>
<td>No/Doesn't Matter</td>
<td>No/Doesn't Matter</td>
<td>4.309</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>Fireworks</td>
<td>Pop Soundtrack</td>
<td>30</td>
<td>65</td>
<td>40</td>
<td>front plaza</td>
<td>None</td>
<td>One</td>
<td>Yes</td>
<td>Yes</td>
<td>6.239</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Based on the 12 variables provided in the dataset, here’s the list of numeric and categorical variables: - <strong>Numerical Variables:</strong> show_length (in minutes); peak_dB_Level (decibels level); crowding_index (crowd density); ratings (average ratings from 0 t0 10).</p>
<ul>
<li><p><strong>Categorical Variables:</strong> bundleID, headliner, music_atmosphere, viewing_zone, dining_bundle, re_entry, live_host, and charity_tie_in, as they represent distinct categories or labels rather than quantities with mathematical meaning.</p></li>
<li><p>I also dropped bundleID from the dataset because it functions solely as a sequential identifier without providing any analytical or predictive value. Including it could potentially create misleading patterns in the model, so excluding it prevents future problems.</p></li>
</ul>
<div id="29c53136-bec9-40b6-b2f8-98eae2e4f778" class="cell" data-execution_count="108">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>night_show <span class="op">=</span> night_show.drop(columns<span class="op">=</span>[<span class="st">"bundleID"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="532086d9-09bb-4a7c-a19e-a8205c5769e9" class="cell" data-execution_count="109">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the columns to convert</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="op">=</span> [<span class="st">"headliner"</span>, <span class="st">"music_atmosphere"</span>, <span class="st">"viewing_zone"</span>, <span class="st">"dining_bundle"</span>,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"re_entry"</span>, <span class="st">"live_host"</span>, <span class="st">"charity_tie_in"</span>]</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to category dtype</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>night_show[categorical_cols] <span class="op">=</span> night_show[categorical_cols].astype(<span class="st">'category'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="1cf2c92a-5141-4c10-97b0-caa09c1105f9" class="cell" data-execution_count="110">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>night_show.info()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 73728 entries, 0 to 73727
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype   
---  ------            --------------  -----   
 0   headliner         73728 non-null  category
 1   music_atmosphere  73728 non-null  category
 2   show_length       73728 non-null  int64   
 3   peak_dB_Level     73728 non-null  int64   
 4   crowding_index    73728 non-null  int64   
 5   viewing_zone      73728 non-null  category
 6   dining_bundle     73728 non-null  category
 7   re_entry          73728 non-null  category
 8   live_host         73728 non-null  category
 9   charity_tie_in    73728 non-null  category
 10  ratings           73728 non-null  float64 
dtypes: category(7), float64(1), int64(3)
memory usage: 2.7 MB</code></pre>
</div>
</div>
<section id="use-the-pandas-get_dummies-function-in-order-to-prepare-these-variables-for-use-in-a-linear-model.-inside-this-function-include-this-argument-drop_first-true.-doing-this-will-save-us-from-the-multicollinearity-problem-that-would-make-our-model-unreliable." class="level4">
<h4 class="anchored" data-anchor-id="use-the-pandas-get_dummies-function-in-order-to-prepare-these-variables-for-use-in-a-linear-model.-inside-this-function-include-this-argument-drop_first-true.-doing-this-will-save-us-from-the-multicollinearity-problem-that-would-make-our-model-unreliable.">Use the pandas get_dummies() function in order to prepare these variables for use in a linear model. Inside this function, include this argument: drop_first = True. Doing this will save us from the multicollinearity problem that would make our model unreliable.</h4>
<div id="e16ede5d-2536-434e-8baf-4c2cc901e3d8" class="cell" data-execution_count="111">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Before dummifying the variables, check to see if the dataset has any null input</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>night_show.isnull().values.<span class="bu">any</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="111">
<pre><code>np.False_</code></pre>
</div>
</div>
<div id="6bd2bded-0ab1-4785-9cda-f95b6fb1eea0" class="cell" data-execution_count="112">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>night_show.columns</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="112">
<pre><code>Index(['headliner', 'music_atmosphere', 'show_length', 'peak_dB_Level',
       'crowding_index', 'viewing_zone', 'dining_bundle', 're_entry',
       'live_host', 'charity_tie_in', 'ratings'],
      dtype='object')</code></pre>
</div>
</div>
<div id="2d1e4f8c-c61f-4e02-a38c-89b884cca97b" class="cell" data-execution_count="113">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>night_show_dm <span class="op">=</span> pd.get_dummies(night_show, drop_first<span class="op">=</span><span class="va">True</span>, columns<span class="op">=</span>[<span class="st">'headliner'</span>, <span class="st">'music_atmosphere'</span>, <span class="st">'show_length'</span>, <span class="st">'peak_dB_Level'</span>,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>       <span class="st">'crowding_index'</span>, <span class="st">'viewing_zone'</span>, <span class="st">'dining_bundle'</span>, <span class="st">'re_entry'</span>,<span class="st">'live_host'</span>, <span class="st">'charity_tie_in'</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="e62deb42-3a70-44f6-979e-19f04533345f" class="cell" data-execution_count="114">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>night_show_dm.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="114">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ratings</th>
<th data-quarto-table-cell-role="th">headliner_Drone Light Show</th>
<th data-quarto-table-cell-role="th">headliner_Fireworks</th>
<th data-quarto-table-cell-role="th">headliner_Live Musical</th>
<th data-quarto-table-cell-role="th">music_atmosphere_Pop Soundtrack</th>
<th data-quarto-table-cell-role="th">show_length_70</th>
<th data-quarto-table-cell-role="th">show_length_110</th>
<th data-quarto-table-cell-role="th">show_length_150</th>
<th data-quarto-table-cell-role="th">peak_dB_Level_85</th>
<th data-quarto-table-cell-role="th">peak_dB_Level_105</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">viewing_zone_boardwalk</th>
<th data-quarto-table-cell-role="th">viewing_zone_castle_courtyard</th>
<th data-quarto-table-cell-role="th">viewing_zone_front plaza</th>
<th data-quarto-table-cell-role="th">dining_bundle_dessert_party</th>
<th data-quarto-table-cell-role="th">dining_bundle_meal_package</th>
<th data-quarto-table-cell-role="th">dining_bundle_snack_voucher</th>
<th data-quarto-table-cell-role="th">re_entry_One</th>
<th data-quarto-table-cell-role="th">re_entry_Unlimited</th>
<th data-quarto-table-cell-role="th">live_host_Yes</th>
<th data-quarto-table-cell-role="th">charity_tie_in_Yes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>4.249</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>4.689</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7.999</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4.309</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>6.239</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>True</td>
</tr>
</tbody>
</table>

<p>5 rows × 23 columns</p>
</div>
</div>
</div>
<div id="4aea5413-e167-470e-87f7-6f9c07708c42" class="cell" data-execution_count="115">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>night_show_dm.columns</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="115">
<pre><code>Index(['ratings', 'headliner_Drone Light Show', 'headliner_Fireworks',
       'headliner_Live Musical', 'music_atmosphere_Pop Soundtrack',
       'show_length_70', 'show_length_110', 'show_length_150',
       'peak_dB_Level_85', 'peak_dB_Level_105', 'crowding_index_60',
       'crowding_index_80', 'crowding_index_100', 'viewing_zone_boardwalk',
       'viewing_zone_castle_courtyard', 'viewing_zone_front plaza',
       'dining_bundle_dessert_party', 'dining_bundle_meal_package',
       'dining_bundle_snack_voucher', 're_entry_One', 're_entry_Unlimited',
       'live_host_Yes', 'charity_tie_in_Yes'],
      dtype='object')</code></pre>
</div>
</div>
</section>
<section id="why-should-the-numeric-input-variables-based-on-this-survey-data-be-dummified" class="level4">
<h4 class="anchored" data-anchor-id="why-should-the-numeric-input-variables-based-on-this-survey-data-be-dummified">Why should the numeric input variables based on this survey data be dummified?</h4>
<p>Numeric input variables from survey data should be converted into dummy variables because even though they appear as numbers, they represent discrete categories rather than continuous measurements. Take <em>show_length</em> for example, it might include values such as 30, 70, 110, and 150 minutes. These values are not part of a linear scale but rather specific options provided by the survey design. Treating them as continuous would incorrectly assume that the difference between 30 and 70 minutes has the same proportional relationship as the difference between 110 and 150 minutes, which may not reflect reality.</p>
<p>By converting these numeric inputs into dummy variables, the model can assign independent effects to each category without imposing misleading linear assumptions. This approach improves both the accuracy and interpretability of the model while ensuring that the analysis respects the categorical structure inherent in survey-based numeric data.</p>
</section>
<section id="it-might-seem-tempting-here-to-just-skip-the-model-building-step-instead-of-building-a-model-we-could-just-rank-the-bundles-by-average-rating-in-descending-order-and-then-just-tell-lobster-land-to-implement-all-the-features-in-the-highest-rated-bundle." class="level4">
<h4 class="anchored" data-anchor-id="it-might-seem-tempting-here-to-just-skip-the-model-building-step-instead-of-building-a-model-we-could-just-rank-the-bundles-by-average-rating-in-descending-order-and-then-just-tell-lobster-land-to-implement-all-the-features-in-the-highest-rated-bundle.">It might seem tempting here to just skip the model-building step – instead of building a model, we could just rank the bundles by average rating, in descending order, and then just tell Lobster Land to implement all the features in the highest-rated bundle.</h4>
<p>Ranking bundles by their average rating might seem ideal, but it hides the true drivers of guest satisfaction. Without building a model, it’s difficult to tell which specific features within each bundle actually influence ratings or how they interact with one another. For example, a highly rated bundle might include both a live musical and unlimited re-entry, but we would not know that the musical boosts satisfaction while the re-entry option reduces it. A conjoint analysis model solves this by estimating the independent effect of each feature across all bundles, allowing Lobster Land to predict how new combinations would perform and design offerings that maximize impact while keeping costs manageable. In short, the model provides a deeper, data-driven understanding of guest preferences that simple ranking cannot achieve.</p>
</section>
<section id="build-a-linear-model-with-your-data-using-the-average-rating-as-the-outcome-variable-and-with-all-of-your-other-variables-other-than-the-bundleid-as-inputs." class="level4">
<h4 class="anchored" data-anchor-id="build-a-linear-model-with-your-data-using-the-average-rating-as-the-outcome-variable-and-with-all-of-your-other-variables-other-than-the-bundleid-as-inputs.">Build a linear model with your data, using the average rating as the outcome variable, and with all of your other variables (other than the bundleID) as inputs.</h4>
<p>I build a linear regression model using all dummified input features to predict the average rating. This allows to estimate how each individual feature contributes to guest satisfaction.</p>
<div id="b2390689-881f-427f-a56b-56e36edafa11" class="cell" data-execution_count="116">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Linear Regression model</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> night_show_dm[[<span class="st">'headliner_Drone Light Show'</span>, <span class="st">'headliner_Fireworks'</span>,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>       <span class="st">'headliner_Live Musical'</span>, <span class="st">'music_atmosphere_Pop Soundtrack'</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>       <span class="st">'show_length_70'</span>, <span class="st">'show_length_110'</span>, <span class="st">'show_length_150'</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>       <span class="st">'peak_dB_Level_85'</span>, <span class="st">'peak_dB_Level_105'</span>, <span class="st">'crowding_index_60'</span>,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>       <span class="st">'crowding_index_80'</span>, <span class="st">'crowding_index_100'</span>, <span class="st">'viewing_zone_boardwalk'</span>,</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>       <span class="st">'viewing_zone_castle_courtyard'</span>, <span class="st">'viewing_zone_front plaza'</span>,</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>       <span class="st">'dining_bundle_dessert_party'</span>, <span class="st">'dining_bundle_meal_package'</span>,</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>       <span class="st">'dining_bundle_snack_voucher'</span>, <span class="st">'re_entry_One'</span>, <span class="st">'re_entry_Unlimited'</span>,</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>       <span class="st">'live_host_Yes'</span>, <span class="st">'charity_tie_in_Yes'</span>]]</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> night_show_dm[<span class="st">"ratings"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="353699ed-a1e0-49b2-8e14-9687eb33a31f" class="cell" data-execution_count="117">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import LinearRegression function from scikit‑learn</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>regressor <span class="op">=</span> LinearRegression()</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>regressor.fit(X, y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="117">
<style>#sk-container-id-2 {
  /* Definition of color scheme common for light and dark mode */
  --sklearn-color-text: #000;
  --sklearn-color-text-muted: #666;
  --sklearn-color-line: gray;
  /* Definition of color scheme for unfitted estimators */
  --sklearn-color-unfitted-level-0: #fff5e6;
  --sklearn-color-unfitted-level-1: #f6e4d2;
  --sklearn-color-unfitted-level-2: #ffe0b3;
  --sklearn-color-unfitted-level-3: chocolate;
  /* Definition of color scheme for fitted estimators */
  --sklearn-color-fitted-level-0: #f0f8ff;
  --sklearn-color-fitted-level-1: #d4ebff;
  --sklearn-color-fitted-level-2: #b3dbfd;
  --sklearn-color-fitted-level-3: cornflowerblue;

  /* Specific color for light theme */
  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));
  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));
  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));
  --sklearn-color-icon: #696969;

  @media (prefers-color-scheme: dark) {
    /* Redefinition of color scheme for dark theme */
    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));
    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));
    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));
    --sklearn-color-icon: #878787;
  }
}

#sk-container-id-2 {
  color: var(--sklearn-color-text);
}

#sk-container-id-2 pre {
  padding: 0;
}

#sk-container-id-2 input.sk-hidden--visually {
  border: 0;
  clip: rect(1px 1px 1px 1px);
  clip: rect(1px, 1px, 1px, 1px);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

#sk-container-id-2 div.sk-dashed-wrapped {
  border: 1px dashed var(--sklearn-color-line);
  margin: 0 0.4em 0.5em 0.4em;
  box-sizing: border-box;
  padding-bottom: 0.4em;
  background-color: var(--sklearn-color-background);
}

#sk-container-id-2 div.sk-container {
  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`
     but bootstrap.min.css set `[hidden] { display: none !important; }`
     so we also need the `!important` here to be able to override the
     default hidden behavior on the sphinx rendered scikit-learn.org.
     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */
  display: inline-block !important;
  position: relative;
}

#sk-container-id-2 div.sk-text-repr-fallback {
  display: none;
}

div.sk-parallel-item,
div.sk-serial,
div.sk-item {
  /* draw centered vertical line to link estimators */
  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));
  background-size: 2px 100%;
  background-repeat: no-repeat;
  background-position: center center;
}

/* Parallel-specific style estimator block */

#sk-container-id-2 div.sk-parallel-item::after {
  content: "";
  width: 100%;
  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);
  flex-grow: 1;
}

#sk-container-id-2 div.sk-parallel {
  display: flex;
  align-items: stretch;
  justify-content: center;
  background-color: var(--sklearn-color-background);
  position: relative;
}

#sk-container-id-2 div.sk-parallel-item {
  display: flex;
  flex-direction: column;
}

#sk-container-id-2 div.sk-parallel-item:first-child::after {
  align-self: flex-end;
  width: 50%;
}

#sk-container-id-2 div.sk-parallel-item:last-child::after {
  align-self: flex-start;
  width: 50%;
}

#sk-container-id-2 div.sk-parallel-item:only-child::after {
  width: 0;
}

/* Serial-specific style estimator block */

#sk-container-id-2 div.sk-serial {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: var(--sklearn-color-background);
  padding-right: 1em;
  padding-left: 1em;
}


/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is
clickable and can be expanded/collapsed.
- Pipeline and ColumnTransformer use this feature and define the default style
- Estimators will overwrite some part of the style using the `sk-estimator` class
*/

/* Pipeline and ColumnTransformer style (default) */

#sk-container-id-2 div.sk-toggleable {
  /* Default theme specific background. It is overwritten whether we have a
  specific estimator or a Pipeline/ColumnTransformer */
  background-color: var(--sklearn-color-background);
}

/* Toggleable label */
#sk-container-id-2 label.sk-toggleable__label {
  cursor: pointer;
  display: flex;
  width: 100%;
  margin-bottom: 0;
  padding: 0.5em;
  box-sizing: border-box;
  text-align: center;
  align-items: start;
  justify-content: space-between;
  gap: 0.5em;
}

#sk-container-id-2 label.sk-toggleable__label .caption {
  font-size: 0.6rem;
  font-weight: lighter;
  color: var(--sklearn-color-text-muted);
}

#sk-container-id-2 label.sk-toggleable__label-arrow:before {
  /* Arrow on the left of the label */
  content: "▸";
  float: left;
  margin-right: 0.25em;
  color: var(--sklearn-color-icon);
}

#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {
  color: var(--sklearn-color-text);
}

/* Toggleable content - dropdown */

#sk-container-id-2 div.sk-toggleable__content {
  max-height: 0;
  max-width: 0;
  overflow: hidden;
  text-align: left;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-2 div.sk-toggleable__content.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-2 div.sk-toggleable__content pre {
  margin: 0.2em;
  border-radius: 0.25em;
  color: var(--sklearn-color-text);
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-2 div.sk-toggleable__content.fitted pre {
  /* unfitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {
  /* Expand drop-down */
  max-height: 200px;
  max-width: 100%;
  overflow: auto;
}

#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {
  content: "▾";
}

/* Pipeline/ColumnTransformer-specific style */

#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-2 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator-specific style */

/* Colorize estimator box */
#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-2 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

#sk-container-id-2 div.sk-label label.sk-toggleable__label,
#sk-container-id-2 div.sk-label label {
  /* The background is the default theme color */
  color: var(--sklearn-color-text-on-default-background);
}

/* On hover, darken the color of the background */
#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

/* Label box, darken color on hover, fitted */
#sk-container-id-2 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator label */

#sk-container-id-2 div.sk-label label {
  font-family: monospace;
  font-weight: bold;
  display: inline-block;
  line-height: 1.2em;
}

#sk-container-id-2 div.sk-label-container {
  text-align: center;
}

/* Estimator-specific */
#sk-container-id-2 div.sk-estimator {
  font-family: monospace;
  border: 1px dotted var(--sklearn-color-border-box);
  border-radius: 0.25em;
  box-sizing: border-box;
  margin-bottom: 0.5em;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-2 div.sk-estimator.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

/* on hover */
#sk-container-id-2 div.sk-estimator:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-2 div.sk-estimator.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Specification for estimator info (e.g. "i" and "?") */

/* Common style for "i" and "?" */

.sk-estimator-doc-link,
a:link.sk-estimator-doc-link,
a:visited.sk-estimator-doc-link {
  float: right;
  font-size: smaller;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-background);
  border-radius: 1em;
  height: 1em;
  width: 1em;
  text-decoration: none !important;
  margin-left: 0.5em;
  text-align: center;
  /* unfitted */
  border: var(--sklearn-color-unfitted-level-1) 1pt solid;
  color: var(--sklearn-color-unfitted-level-1);
}

.sk-estimator-doc-link.fitted,
a:link.sk-estimator-doc-link.fitted,
a:visited.sk-estimator-doc-link.fitted {
  /* fitted */
  border: var(--sklearn-color-fitted-level-1) 1pt solid;
  color: var(--sklearn-color-fitted-level-1);
}

/* On hover */
div.sk-estimator:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover,
div.sk-label-container:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover,
div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

/* Span, style for the box shown on hovering the info icon */
.sk-estimator-doc-link span {
  display: none;
  z-index: 9999;
  position: relative;
  font-weight: normal;
  right: .2ex;
  padding: .5ex;
  margin: .5ex;
  width: min-content;
  min-width: 20ex;
  max-width: 50ex;
  color: var(--sklearn-color-text);
  box-shadow: 2pt 2pt 4pt #999;
  /* unfitted */
  background: var(--sklearn-color-unfitted-level-0);
  border: .5pt solid var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted span {
  /* fitted */
  background: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3);
}

.sk-estimator-doc-link:hover span {
  display: block;
}

/* "?"-specific style due to the `<a>` HTML tag */

#sk-container-id-2 a.estimator_doc_link {
  float: right;
  font-size: 1rem;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-background);
  border-radius: 1rem;
  height: 1rem;
  width: 1rem;
  text-decoration: none;
  /* unfitted */
  color: var(--sklearn-color-unfitted-level-1);
  border: var(--sklearn-color-unfitted-level-1) 1pt solid;
}

#sk-container-id-2 a.estimator_doc_link.fitted {
  /* fitted */
  border: var(--sklearn-color-fitted-level-1) 1pt solid;
  color: var(--sklearn-color-fitted-level-1);
}

/* On hover */
#sk-container-id-2 a.estimator_doc_link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

#sk-container-id-2 a.estimator_doc_link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
}
</style><div id="sk-container-id-2" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator fitted sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox" checked=""><label for="sk-estimator-id-2" class="sk-toggleable__label fitted sk-toggleable__label-arrow"><div><div>LinearRegression</div></div><div><a class="sk-estimator-doc-link fitted" rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.6/modules/generated/sklearn.linear_model.LinearRegression.html">?<span>Documentation for LinearRegression</span></a><span class="sk-estimator-doc-link fitted">i<span>Fitted</span></span></div></label><div class="sk-toggleable__content fitted"><pre>LinearRegression()</pre></div> </div></div></div></div>
</div>
</div>
<div id="a86aa868-a542-49b4-b954-b4b35ed9dc3c" class="cell" data-execution_count="118">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>regressor.intercept_</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Intercept: </span><span class="sc">{</span>regressor<span class="sc">.</span>intercept_<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept: 4.953</code></pre>
</div>
</div>
<div id="37616f71-e460-4d83-ace4-9d975a359e31" class="cell" data-execution_count="119">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define outcome and predictors</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> night_show_dm[<span class="st">'ratings'</span>]</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>X_model <span class="op">=</span> night_show_dm.drop(columns<span class="op">=</span>[<span class="st">'ratings'</span>])</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add intercept term</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>X_model <span class="op">=</span> sm.add_constant(X_model)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert boolean columns to numeric</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>bool_cols <span class="op">=</span> X_model.select_dtypes(include<span class="op">=</span>[<span class="st">'bool'</span>]).columns</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>X_model[bool_cols] <span class="op">=</span> X_model[bool_cols].astype(<span class="bu">int</span>)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>X_model <span class="op">=</span> X_model.astype(<span class="bu">float</span>)</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>linear_model <span class="op">=</span> sm.OLS(y, X_model).fit()</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(linear_model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                ratings   R-squared:                       0.345
Model:                            OLS   Adj. R-squared:                  0.345
Method:                 Least Squares   F-statistic:                     1766.
Date:                Mon, 12 Jan 2026   Prob (F-statistic):               0.00
Time:                        22:53:46   Log-Likelihood:            -1.4678e+05
No. Observations:               73728   AIC:                         2.936e+05
Df Residuals:                   73705   BIC:                         2.938e+05
Df Model:                          22                                         
Covariance Type:            nonrobust                                         
===================================================================================================
                                      coef    std err          t      P&gt;|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                               4.9533      0.031    158.283      0.000       4.892       5.015
headliner_Drone Light Show          0.0178      0.018      0.964      0.335      -0.018       0.054
headliner_Fireworks                 0.0009      0.018      0.046      0.963      -0.035       0.037
headliner_Live Musical              1.0299      0.018     55.801      0.000       0.994       1.066
music_atmosphere_Pop Soundtrack    -0.7130      0.013    -54.634      0.000      -0.739      -0.687
show_length_70                      0.7179      0.018     38.898      0.000       0.682       0.754
show_length_110                     0.9709      0.018     52.608      0.000       0.935       1.007
show_length_150                     0.7038      0.018     38.136      0.000       0.668       0.740
peak_dB_Level_85                    0.0165      0.016      1.034      0.301      -0.015       0.048
peak_dB_Level_105                  -0.8872      0.016    -55.507      0.000      -0.919      -0.856
crowding_index_60                   0.2230      0.018     12.085      0.000       0.187       0.259
crowding_index_80                   0.2323      0.018     12.588      0.000       0.196       0.268
crowding_index_100                 -0.6046      0.018    -32.760      0.000      -0.641      -0.568
viewing_zone_boardwalk              0.3889      0.018     21.070      0.000       0.353       0.425
viewing_zone_castle_courtyard       0.3560      0.018     19.291      0.000       0.320       0.392
viewing_zone_front plaza            0.3389      0.018     18.362      0.000       0.303       0.375
dining_bundle_dessert_party        -0.0028      0.018     -0.154      0.877      -0.039       0.033
dining_bundle_meal_package          0.0033      0.018      0.177      0.860      -0.033       0.039
dining_bundle_snack_voucher        -0.0922      0.018     -4.993      0.000      -0.128      -0.056
re_entry_One                        0.2968      0.016     18.569      0.000       0.265       0.328
re_entry_Unlimited                 -1.5920      0.016    -99.604      0.000      -1.623      -1.561
live_host_Yes                       0.8425      0.013     64.555      0.000       0.817       0.868
charity_tie_in_Yes                  0.2418      0.013     18.529      0.000       0.216       0.267
==============================================================================
Omnibus:                      584.467   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              394.485
Skew:                          -0.030   Prob(JB):                     2.18e-86
Kurtosis:                       2.647   Cond. No.                         10.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="display-the-coefficient-values-of-your-model-inputs." class="level4">
<h4 class="anchored" data-anchor-id="display-the-coefficient-values-of-your-model-inputs.">Display the coefficient values of your model inputs.</h4>
<p>I extract and display the model’s coefficients to understand the direction and strength of each feature’s impact on ratings.</p>
<div id="e7aa8f8a-d7a9-424f-94a4-94007f496a34" class="cell" data-execution_count="120">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>coef_df <span class="op">=</span> pd.DataFrame(regressor.coef_, X.columns, columns<span class="op">=</span>[<span class="st">'Coefficient'</span>])</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>coef_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="120">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">headliner_Drone Light Show</th>
<td>0.017789</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">headliner_Fireworks</th>
<td>0.000853</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">headliner_Live Musical</th>
<td>1.029869</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">music_atmosphere_Pop Soundtrack</th>
<td>-0.713001</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">show_length_70</th>
<td>0.717907</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">show_length_110</th>
<td>0.970937</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">show_length_150</th>
<td>0.703843</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">peak_dB_Level_85</th>
<td>0.016527</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">peak_dB_Level_105</th>
<td>-0.887189</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">crowding_index_60</th>
<td>0.223038</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">crowding_index_80</th>
<td>0.232322</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">crowding_index_100</th>
<td>-0.604624</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">viewing_zone_boardwalk</th>
<td>0.388865</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">viewing_zone_castle_courtyard</th>
<td>0.356038</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">viewing_zone_front plaza</th>
<td>0.338891</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">dining_bundle_dessert_party</th>
<td>-0.002845</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">dining_bundle_meal_package</th>
<td>0.003259</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">dining_bundle_snack_voucher</th>
<td>-0.092152</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">re_entry_One</th>
<td>0.296802</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">re_entry_Unlimited</th>
<td>-1.592003</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">live_host_Yes</th>
<td>0.842467</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">charity_tie_in_Yes</th>
<td>0.241810</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="write-two-three-paragraphs-for-lobster-land-management-about-what-your-model-is-showing-you." class="level4">
<h4 class="anchored" data-anchor-id="write-two-three-paragraphs-for-lobster-land-management-about-what-your-model-is-showing-you.">Write two-three paragraphs for Lobster Land management about what your model is showing you.</h4>
<p>Dear Lobster Land Management Team,</p>
<p>I wanted to share some important findings from our conjoint analysis that can help guide decisions around evening entertainment programming. By examining guest survey responses across different features—headliner type, show length, sound levels, re-entry policies, and more—the analysis provides a clearer picture of what actually drives satisfaction and what might be holding the park back. The results show some strong patterns. Live Musical performances (coefficient of 1.03) and having a live host (0.84) make a significant positive impact on guest ratings, while unlimited re-entry (-1.59) and extremely loud sound at 105 dB (-0.89) actively hurt the experience. Shows running around 110 minutes (0.97) appear to be the ideal length, and high crowding levels (negative 0.60 at maximum capacity) clearly diminish satisfaction. These numbers help clarify not just what guests prefer, but how much each element matters when prioritizing investments and operational changes.</p>
<p>From a short-term planning perspective, there are several actionable takeaways. The 110-minute show format seems to be the best option where guests feel they’re getting a full experience without it dragging on or feeling rushed. Although the unlimited re-entry sounds captivating, guests actually prefer having just one opportunity to leave and return, likely because unlimited access signals overcrowding or diminishes the sense of exclusivity. A simple re-entry policy could make guests feel they’re getting more value while also helping manage crowds better. Live musicals clearly offer the best experiences, but they also come with higher costs, tighter schedules, and more moving parts than drone shows or fireworks. The team will need to think carefully about when and how often to host live performances, especially during busy seasons when multiple shows a night could stretch both staff and resources.</p>
<p>Looking at longer-term strategy, the data suggests some interesting opportunities for tiered experiences. The park should offer premium ticket packages which allow guests to book particular less crowded viewing spots within standard capacity areas. This allows guests who value personal space to pay for that comfort while offering more budget-conscious visitors access at lower price points. Live hosts and charity partnerships, though subtle in impact, show how genuine connection and purpose-driven storytelling can make experiences more memorable and unique. On the dining side, bundles don’t boost satisfaction much, and snack vouchers may even hurt it, as guests often see them as low-value add-ons rather than real enhancements.</p>
<p>The key take-away is: prioritize live performances with engaging hosts, keep 110-minute show lengths, keep the sound levels part of the experience without being too overpowering, and manage crowds so visitors have room to enjoy themselves. By focusing on what matters most to customers (authentic experiences, good pacing, and making the evening special), the park can differentiate and create the evenings guests will come back for.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/nhattran309\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>